import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {financialAtYear,financialYears} from '../lib/financial-year.mjs';
import {captureSelectionTrace,validEntryMetadata} from '../lib/entry-route.mjs';
import {selectionJourney} from '../lib/selection-journey.mjs';
import {defaultMovementState,restoreMovementState} from '../lib/movement-model.mjs';
import {inspectEntryPlan,reconcileScenarioCases,mergeScenarioPlans,reviewSignature} from '../lib/scenario-workspace.mjs';
import {validateScenarioBackup} from '../lib/scenario-management.mjs';
const companies=JSON.parse(fs.readFileSync(new URL('../public/data/financial-companies.json',import.meta.url)));
test('v48 current financial scatter reconstructs the approved axes for every company',()=>{for(const c of companies){const r=financialAtYear(c,c.year);assert.deepEqual(r.scatterAxes,c.scatterAxes);}});
test('v48 historical year uses its own KPI scores and ranking dimensions without latest-year fallback',()=>{const c=companies[0],r=financialAtYear(c,1403);assert.deepEqual(r.dimensions,c.yearlyDimensions['1403']);const x=c.kpiHistory['144'].find(p=>p.year===1403).score*.55+c.kpiHistory['186'].find(p=>p.year===1403).score*.45;assert.equal(r.scatterAxes.scatterOperationalGrowth,Math.round(x*1e4)/1e4);assert.notDeepEqual(r.scatterAxes,c.scatterAxes);const absent=financialAtYear(c,1390);assert.equal(absent.score,null);assert.ok(Object.values(absent.scatterAxes).every(x=>x===null));assert.deepEqual(absent.dimensions,{});assert.ok(!financialYears(companies).includes(1390));});
const opportunity={key:'parent:24',name:'فلزات',parentId:24,parentName:'حوزه اصلی',child:false,macro:70,detail:60,management:4,entryPriority:70,horizon:'core'};
function fixture(){const base=defaultMovementState();base.mission[24]='مجاز';base.board[24]={score:4,reason:'توسعه شبکه مشتری'};const trace=captureSelectionTrace(opportunity,base,{x:7,dynamicY:6},1406,'مرجع');base.baskets[1406]={[opportunity.key]:{share:0,priorityRank:1,parentId:24,entryMode:'trade',selectionTrace:trace}};return base;}
test('v48 chosen trade route and independent selection evidence survive hydration, freeze and case handoff',()=>{const base=fixture();const restored=restoreMovementState(base,[{id:24,priority:70}],[]);assert.equal(restored.baskets[1406]['parent:24'].entryMode,'trade');assert.deepEqual(restored.baskets[1406]['parent:24'].selectionTrace,base.baskets[1406]['parent:24'].selectionTrace);const {plans,errors}=inspectEntryPlan(base.baskets,[opportunity],'priority');assert.deepEqual(errors,[]);assert.equal(plans[0].entryMode,'trade');const cases=reconcileScenarioCases({},[{id:'s',name:'سناریو',plans}],['s']);assert.equal(cases['s:1406:parent:24'].entryMode,'trade');assert.notEqual(reviewSignature(base,'entry'),reviewSignature({...base,baskets:{1406:{'parent:24':{...base.baskets[1406]['parent:24'],entryMode:'direct'}}}},'entry'));});
test('v48 journey keeps selection-time scores when subsequent policy or weights change',()=>{const base=fixture(),trace=structuredClone(base.baskets[1406]['parent:24'].selectionTrace);base.selectionWeights={macro:100,detail:0,board:0};base.board[24].score=1;const input={baskets:base.baskets,opportunities:[{...opportunity,entryPriority:25}],scenario:{id:'s',revision:2,base}};const row=selectionJourney(input,1406)[0];assert.equal(row.mode,'trade');assert.deepEqual(row.trace,trace);assert.equal(row.currentPriority,25);assert.equal(row.trace.scores.management,4);assert.equal(row.recorded,true);});
test('v48 entry route differences create conflicts instead of silently merging two programs',()=>{const plans=[{...opportunity,year:1406,share:0,priorityRank:1,entryMode:'trade'}];const result=mergeScenarioPlans([{id:'a',name:'A',plans},{id:'b',name:'B',plans:plans.map(p=>({...p,entryMode:'direct'}))}],1406);assert.equal(result.conflicts.length,1);});
test('v48 malformed route or selection history is rejected before restore',()=>{const base=fixture(),w={version:31,base,scenarios:[],snapshots:[],activeScenarioId:'',selectedSnapshots:[],conflictChoices:{},capital:{cases:{},financialByYear:{},portfolioActions:{}}};validateScenarioBackup(w);assert.ok(validEntryMetadata(base.baskets[1406]['parent:24']));base.baskets[1406]['parent:24'].selectionTrace.gates=null;assert.throws(()=>validateScenarioBackup(w));base.baskets[1406]['parent:24'].selectionTrace=undefined;base.baskets[1406]['parent:24'].entryMode='invalid';assert.throws(()=>validateScenarioBackup(w));});
