"use client";
import {type CapitalOutput,FUNDING_SOURCES} from "@/lib/capital-allocation.mjs";
import {summarizeCapital} from "@/lib/capital-presentation.mjs";
const fa=(v:number|null)=>v==null?"نامشخص":v.toLocaleString("fa-IR",{maximumFractionDigits:2});
export default function CapitalExecutiveSummary({output,annualOutputs,contextName,signal,financeStatuses,blockedYears,onYear,onOpen}:{output:CapitalOutput;annualOutputs:CapitalOutput[];contextName:string;signal:string;financeStatuses:Record<number,string>;blockedYears:number[];onYear:(year:number)=>void;onOpen:(id:string)=>void}) {
 const summary=summarizeCapital(output);
 const attention=output.results.filter(r=>!r.validation.valid||r.financialReviewRequired||r.deferred>0);
 const max=Math.max(1,...annualOutputs.map(o=>summarizeCapital(o).knownNeed));
 return <div className="capital-executive-v36">
  <section className="executive-decision-banner"><div><span>جمع‌بندی تخصیص سرمایه · سال {output.year.toLocaleString("fa-IR",{useGrouping:false})}</span><h3>{contextName}</h3><p>{signal}</p></div><div className="executive-coverage"><small>پوشش نیاز معتبر کل سبد</small><strong>{summary.coverage==null?"نامشخص":`${fa(summary.coverage*100)}٪`}</strong><span>{summary.incomplete?"نیاز کل سبد هنوز تکمیل نشده":"بر اساس نیازهای ثبت‌شده"}</span></div></section>
  <section className="executive-v36-metrics">{[["نیاز کل سبد",summary.need],["تأمین‌شده",output.totalExecuted],["کسری کل سبد",summary.gap],["ظرفیت آزاد قابل تخصیص",output.freeCapacity]].map(([name,value])=><article key={String(name)}><span>{name}</span><b>{fa(value as number|null)}</b><small>میلیارد تومان</small></article>)}</section>
  <section className="executive-readiness"><h4>سه کنترل مستقل پیش از ثبت تصمیم</h4><div><span><b>ارقام سال</b>{!output.financialValidation.valid?"ناقص یا نامعتبر":financeStatuses[output.year]==="confirmed"?"تأیید شده":financeStatuses[output.year]==="sample"?"آموزشی؛ نیازمند جایگزینی":"در انتظار تأیید"}</span><span><b>پرونده‌ها</b>{summary.incomplete?`${fa(summary.incomplete)} پرونده ناقص`:summary.review?`${fa(summary.review)} پرونده نیازمند بازبینی مالی`:"مانع ورودی ثبت‌شده ندارد"}</span><span><b>تأمین منابع</b>{blockedYears.includes(output.year)?"تعارض سناریو":output.reservationConflict?"توقف به علت تعارض رزروها":!output.policyValid?"سیاست ناقص":output.liquidityBlocked?"توقف به علت کسری نقد":summary.gap==null?"قابل جمع‌بندی نیست":summary.gap>0?"دارای کسری تأمین":"نیاز معتبر تأمین شده"}</span></div></section>
  <section className="executive-next-decisions"><header><h4>تصمیم‌هایی که باید گرفته شوند</h4><span>{fa(attention.length)} پرونده نیازمند پیگیری</span></header>{summary.incomplete>0&&<p className="executive-incomplete-note">نیاز معتبر ثبت‌شده {fa(summary.knownNeed)} و کسری همان پرونده‌ها {fa(summary.knownGap)} میلیارد تومان است؛ این اعداد جمع کامل سبد نیستند.</p>}<div className="table-scroll"><table><thead><tr><th>طرح</th><th>تصمیم / مانع</th><th>نیاز سال</th><th>تأمین</th><th>کسری</th><th>اقدام</th></tr></thead><tbody>{attention.map(r=><tr key={r.id}><td><b>{r.name}</b><small>{r.needType.replace("CAPEX","سرمایه‌گذاری")}</small></td><td>{r.financialReviewRequired?"بازبینی پرونده منتقل‌شده":r.decision}<small>{r.reason}</small></td><td>{r.validation.valid?fa(r.annualNeed):"نامشخص"}</td><td>{fa(r.executed)}</td><td>{r.validation.valid?fa(r.deferred):"نامشخص"}</td><td><button onClick={()=>onOpen(r.id)}>بررسی پرونده</button></td></tr>)}</tbody></table></div>{!attention.length&&<p>پرونده نیازمند پیگیری در خروجی فعلی ثبت نشده است. تأیید تصمیم را پس از کنترل ارقام و سیاست تأمین ثبت کنید.</p>}</section>
  <section className="executive-financing-summary"><h4>ترکیب منابع تخصیص‌یافته</h4><div>{Object.entries(output.used).filter(([,v])=>v>0).map(([k,v])=><article className={`source-${k}`} key={k}><span>{FUNDING_SOURCES[k as keyof typeof FUNDING_SOURCES].label}</span><b>{fa(v)} <small>میلیارد تومان</small></b><i><em style={{width:`${output.totalExecuted?100*v/output.totalExecuted:0}%`}}/></i></article>)}</div>{!output.totalExecuted&&<p>تخصیصی ثبت نشده است؛ دلیل توقف را در جدول تصمیم‌ها بررسی کنید.</p>}</section>
  <section className="executive-yearly-summary"><header><h4>نمای چندساله نیاز و تأمین</h4><p>نیاز ناقص به‌صورت نامشخص نمایش داده می‌شود؛ برای بررسی، سال را انتخاب کنید.</p></header><div className="executive-years">{annualOutputs.map(o=>{const s=summarizeCapital(o);return <button key={o.year} className={o.year===output.year?"active":""} onClick={()=>onYear(o.year)} aria-label={`جمع‌بندی سال ${o.year.toLocaleString("fa-IR",{useGrouping:false})}`}><b>{o.year.toLocaleString("fa-IR",{useGrouping:false})}</b><div className={`year-capital-bars ${s.need==null?"unknown":""}`}><i style={{height:`${100*s.knownNeed/max}%`}}/><em style={{height:`${100*o.totalExecuted/max}%`}}/></div><span>نیاز {fa(s.need)}</span><span>تأمین {fa(o.totalExecuted)}</span><small>{blockedYears.includes(o.year)?"تعارض سناریو":s.incomplete?"پرونده ناقص":s.review?"بازبینی پرونده":financeStatuses[o.year]==="confirmed"?"ارقام تأیید شده":"ارقام نیازمند تأیید"}</small></button>})}</div><footer>مبالغ: میلیارد تومان · آبی: نیاز معتبر ثبت‌شده · سبز: تأمین‌شده</footer></section>
 </div>;
}
