"use client";
import {useState} from "react";
import {FUNDING_SOURCES,SOURCE_WATERFALL,allocationSourceRows,type CapitalOutput,type SourcePolicy} from "@/lib/capital-allocation.mjs";
const n=(v:number)=>v.toLocaleString("fa-IR",{maximumFractionDigits:1});
export default function CapitalDecisionDesk({output,contextName,financeConfirmed,sourcePolicy,onOpen,onSources,onPolicy}:{output:CapitalOutput;contextName:string;financeConfirmed:boolean;sourcePolicy?:SourcePolicy;onOpen:(id:string)=>void;onSources:()=>void;onPolicy:()=>void}) {
 const [query,setQuery]=useState(""); const [filter,setFilter]=useState("همه طرح‌ها");
 const valid=output.results.filter(r=>r.validation.valid);const incomplete=output.results.length-valid.length;
 const need=valid.reduce((a,r)=>a+r.annualNeed,0);const gap=valid.reduce((a,r)=>a+r.deferred,0);
 const rows=output.results.filter(r=>r.name.includes(query.trim())&&(filter==="همه طرح‌ها"||filter==="ورودی ناقص"&&!r.validation.valid||filter==="دارای کسری"&&r.validation.valid&&r.deferred>0||filter==="تأمین کامل"&&r.validation.valid&&r.deferred===0));
 return <section className="capital-decision-desk">
  <header className="desk-heading"><div><span>میز تصمیم تخصیص سرمایه</span><h3>از نیاز طرح تا تصمیم تأمین</h3><p>{contextName} · سال {output.year.toLocaleString("fa-IR",{useGrouping:false})} · مبالغ به میلیارد تومان</p></div><button onClick={()=>window.print()}>چاپ خلاصه جلسه</button></header>
  <div className="desk-metrics">{[["نیاز معتبر طرح‌ها",need,"فقط پرونده‌های دارای ورودی کامل"],["ظرفیت منابع",output.totalCapacity,"با رعایت سقف مشترک بدهی"],["تأمین‌شده",output.totalExecuted,"نتیجه تخصیص؛ نه تأیید اجرای طرح"],["کسری تأمین",gap,"بخش تأمین‌نشده نیازهای معتبر"]].map(([label,value,help],i)=><article key={String(label)} className={`metric-${i}`}><span>{label}</span><strong>{n(Number(value))}</strong><small>{help}</small></article>)}</div>
  <div className="desk-status" role="status"><b>{!financeConfirmed?"پیش‌نمایش؛ ارقام مالی هنوز تأیید نشده‌اند":incomplete?"جمع‌بندی ناقص؛ پرونده‌ها نیازمند تکمیل‌اند":!output.policyValid?"سیاست تأمین نیازمند تکمیل است":output.liquidityBlocked?"تخصیص به علت کسری نقد متوقف است":"محاسبات بر اساس ورودی فعلی"}</b><span>{incomplete>0?`${n(incomplete)} پرونده ناقص در جمع نیاز معتبر منظور نشده؛ نیاز واقعی سبد هنوز قطعی نیست.`:"تأمین منابع، بررسی اقتصادی و تصویب مدیریتی سه موضوع مستقل هستند."}</span></div>
  <div className="desk-table-heading"><div><h4>طرح‌ها و اقدام بعدی</h4><span>{n(rows.length)} از {n(output.results.length)} طرح</span></div><div className="desk-filters"><input aria-label="جست‌وجوی طرح در میز تصمیم" placeholder="جست‌وجوی طرح…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="فیلتر وضعیت تأمین" value={filter} onChange={e=>setFilter(e.target.value)}>{["همه طرح‌ها","ورودی ناقص","دارای کسری","تأمین کامل"].map(s=><option key={s}>{s}</option>)}</select></div></div>
  <div className="table-scroll"><table className="desk-projects"><thead><tr><th>طرح و نوع نیاز</th><th>نیاز سال</th><th>تأمین‌شده</th><th>کسری</th><th>منابع تأمین پیشنهادی موتور</th><th>وضعیت تأمین / مانع اصلی</th><th>اقدام بعدی</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><small className="desk-need-type">{r.needType.replace("CAPEX","سرمایه‌گذاری")}</small><small>{r.entryRank?`رتبه پیشنهادی ورود ${n(r.entryRank)} · `:""}{r.validation.valid?"ورودی کامل":"ورودی ناقص"}</small></td><td>{r.validation.valid?n(r.annualNeed):"نامشخص"}</td><td>{n(r.executed)}</td><td>{r.validation.valid?n(r.deferred):"نامشخص"}</td><td className="desk-project-sources">{Object.entries(r.allocations).filter(([,value])=>value>0).map(([key,value])=><div className={`funding-source-chip source-${key}`} key={key}><span>{FUNDING_SOURCES[key as keyof typeof FUNDING_SOURCES].label}</span><b>{n(value)}</b></div>)}{r.executed===0&&<span className="source-no-funding">در شرایط فعلی منبعی تخصیص نیافت</span>}<details><summary>ترتیب منابع قابل بررسی</summary><small>{(sourcePolicy?.orders?.[r.needType]??SOURCE_WATERFALL[r.needType]??[]).map(k=>FUNDING_SOURCES[k].label).join(" ← ")}</small><small>ترتیب سیاست است؛ بدون ظرفیت و تحقق شروط، تعهد تأمین محسوب نمی‌شود.</small></details></td><td><span className={`desk-tag ${r.validation.valid&&r.deferred===0?"funded":"attention"}`}>{r.validation.valid?r.decision:"نیازمند تکمیل"}</span><small>{r.reason}</small><small className="desk-review-label">{r.financialReviewRequired?"بازبینی مالی پرونده لازم است":"بازبینی پرونده: مانع ثبت‌شده ندارد"}</small>{r.validation.valid&&<div className="desk-funding-bar" aria-label={`تأمین ${n(r.executed)} از ${n(r.annualNeed)}`}><i style={{width:`${Math.min(100,100*r.executed/r.annualNeed)}%`}}/></div>}</td><td><button onClick={()=>onOpen(r.id)}>{!r.validation.valid?"تکمیل پرونده":r.deferred>0?"بررسی کسری":"مشاهده پرونده"}</button></td></tr>)}</tbody></table></div>
  {!rows.length&&<p className="desk-empty">{output.results.length?"طرحی با این فیلتر پیدا نشد.":"برای این سال پرونده‌ای در دسترس نیست. برنامه سناریو را انتخاب یا یک طرح مستقل ثبت کنید."}</p>}
  <section className="desk-source-section"><header><div><h4>منابع؛ چه مقدار واقعاً آزاد است؟</h4><p>رزرو مصرف‌نشده برای تعهد همان طرح محفوظ می‌ماند.</p></div><button onClick={onSources}>ویرایش ظرفیت منابع</button></header><div className="table-scroll"><table><thead><tr><th>منبع</th><th>ظرفیت اسمی</th><th>تخصیص‌یافته</th><th>رزرو مصرف‌نشده</th><th>مانده منبع</th></tr></thead><tbody>{allocationSourceRows(output).map(r=><tr key={r.key} className={r.key.includes("Debt")?"desk-debt-row":""}><td>{r.label}{r.key.includes("Debt")&&<small>مشمول سقف مشترک بدهی</small>}</td><td>{n(r.capacity)}</td><td>{n(r.used)}</td><td>{n(r.reserved)}</td><td>{n(r.remaining)}</td></tr>)}</tbody></table></div><div className="desk-source-foot"><span>سقف مشترک بدهی: <b>{n(output.capacity.debtCeiling)}</b></span><span>ظرفیت آزاد قابل تخصیص با شروط فعلی: <b>{n(output.freeCapacity)}</b></span><button onClick={onPolicy}>تنظیم تقدم منابع</button></div><small>مانده هر منبع مستقل نمایش داده شده است؛ جمع مانده بدهی‌ها بدون اعمال سقف مشترک، ظرفیت قابل استفاده نیست.</small></section>
  <div className="desk-print-only"><h4>موارد لازم برای صورت‌جلسه</h4><p>تصمیم پیشنهادی: .............................................</p><p>شروط تصویب و مسئول پیگیری: .............................................</p><p>مهلت اقدام و تاریخ بازبینی: .............................................</p><p>تاریخ تهیه: {new Date().toLocaleDateString("fa-IR")} · این گزارش نمایش ورودی جاری است و به‌تنهایی مصوبه نیست.</p></div>
 </section>;
}
