"use client";
import {ENTRY_MODES} from "@/lib/entry-route.mjs";
import {useState} from "react";
import {ArrowLeft,ArrowRight,CheckCircle2,CircleHelp} from "lucide-react";
import {FUNDING_SOURCES,type CapitalOutput,type CapitalTraceStage,type FundingSource} from "@/lib/capital-allocation.mjs";
import {capitalStory,sourceDecision,STORY_PHASES} from "@/lib/capital-story.mjs";
import {reviewCapitalProject} from "@/lib/capital-review.mjs";
const fa=(n:number|null|undefined)=>n==null?"نامشخص":n.toLocaleString("fa-IR",{maximumFractionDigits:2});
const colors:Record<FundingSource,string>={internal:"#187a68",shortDebt:"#3574ca",longDebt:"#7b58b1",partner:"#bd842c",disposal:"#c3654f"};
const basis={managerial:"رتبه مصوب مدیریت",entry:"رتبه برنامه ورود",score:"امتیاز اولویت و قواعد رفع تساوی"};
const holders=(rows:{name:string;amount:number}[])=>rows.map(r=>`${r.name} (${fa(r.amount)})`).join("، ");
function Amount({label,value,kind}:{label:string;value:number|null|undefined;kind?:string}){return <div className={`story-amount ${kind??''}`}><span>{label}</span><strong>{fa(value)}</strong><small>میلیارد تومان</small></div>;}
function SourceGraphic({stage}:{stage:CapitalTraceStage}) {
 const segments=[{label:'مصرف نهایی طرح‌های مقدم',amount:stage.usedByEarlier,color:'#778a9a'},{label:'موقت همین طرح در مراحل قبلی',amount:stage.temporaryBefore,color:'#6e9dcc'},{label:'رزرو دیگر طرح‌ها',amount:stage.reservedForOthers,color:'#c39b51'},{label:'مانده قبل از سقف بدهی و مجوزها',amount:stage.sourceRemaining,color:colors[stage.source!]}];
 return <div className="story-source-graphic"><header><b>ظرفیت منبع چگونه به مانده این مرحله رسید؟</b><span>ظرفیت قابل اتکای سال: <strong>{fa(stage.nominalCapacity)}</strong></span></header><div className="story-capacity-bar" role="img" aria-label={segments.map(s=>`${s.label}: ${fa(s.amount)}`).join('؛ ')}>{segments.map(s=><i key={s.label} style={{width:`${100*(s.amount??0)/Math.max(.01,stage.nominalCapacity)}%`,background:s.color}}/>)}</div><div className="story-capacity-legend">{segments.map(s=><span key={s.label}><i style={{background:s.color}}/><span>{s.label}</span><b>{fa(s.amount)}</b></span>)}</div></div>;
}
export default function CapitalProjectReview({project,onEdit,onResources,onPolicy,onDecision,initialEvent=0}:{project:CapitalOutput['results'][number];onEdit?:()=>void;onResources?:()=>void;onPolicy?:()=>void;onDecision?:()=>void;initialEvent?:number}) {
 const events=capitalStory(project);const [position,setPosition]=useState(initialEvent);
 const index=Math.max(0,Math.min(position,events.length-1));const event=events[index];
 const visitedPhases=new Set(events.slice(0,index+1).map(e=>e.phase));
 const review=reviewCapitalProject(project);const stage=event.traceIndex==null?null:project.trace[event.traceIndex];
 const decision=event.traceIndex==null?null:sourceDecision(project,event.traceIndex);
 const action=review.action==='case'?{label:'تکمیل پرونده',run:onEdit}:review.action==='resources'?{label:'بررسی و ویرایش منابع',run:onResources}:review.action==='policy'?{label:'بررسی قواعد تأمین',run:onPolicy}:{label:'مرور و ثبت تصمیم',run:onDecision};
 const result=event.kind==='result';
 return <section className="capital-story" aria-label={`مسیر تأمین ${project.name}`}>
  <header className="story-header"><div><span>بررسی یک طرح · سال {project.year.toLocaleString('fa-IR',{useGrouping:false})}</span><h3>{project.name}</h3></div>{onEdit&&<button className="story-edit" onClick={onEdit}>ویرایش نیاز و شروط</button>}</header>
  <div className="project-decision-answer"><b>پاسخ پرونده: {project.decision}</b><p>نیاز {project.validation.valid?fa(project.annualNeed):'نامشخص'} · تأمین نهایی {fa(project.executed)} · کسری {project.validation.valid?fa(project.deferred):'نامشخص'} میلیارد تومان</p><p>{Object.entries(project.allocations).filter(([,n])=>n>0).map(([key,n])=>`${FUNDING_SOURCES[key as FundingSource].label}: ${fa(n)}`).join(' · ')||'منبع نهایی تخصیص نیافته است.'}</p><p>{project.reason}</p><small>مبالغ این خلاصه نتیجه نهایی‌اند؛ مراحل پایین، مسیر رسیدن به همین نتیجه را بازپخش می‌کنند.</small></div>
  <div className="story-metrics"><Amount label="نیاز سال" value={project.validation.valid?project.annualNeed:null}/><Amount label={result?'تأمین نهایی':'تأمین موقت تا این مرحله'} value={event.temporary} kind="positive"/><Amount label={result?'کسری نهایی':'نیاز باقی‌مانده'} value={event.remaining} kind="gap"/></div>
  <ol className="story-phases" aria-label="مسیر بررسی">{STORY_PHASES.map((label,i)=><li key={label} aria-current={event.phase===i?'step':undefined} className={event.phase===i?'active':event.phase>i?(visitedPhases.has(i)?'done':'not-assessed'):''}><span>{i<event.phase&&visitedPhases.has(i)?<CheckCircle2 size={16}/>:fa(i+1)}</span>{label}{i<event.phase&&!visitedPhases.has(i)&&<small>بررسی نشد</small>}</li>)}</ol>
  <section className="story-active" aria-live="polite" aria-atomic="true" data-event={event.id}>
   <header><span>مرحله {fa(index+1)} از {fa(events.length)}</span><h4>{event.title}</h4></header>
   {event.kind==='entry'&&<><p className="story-lead">{project.sourceKind==='independent'?'این پرونده به‌صورت پروژه مستقل وارد تخصیص شده است؛ امتیاز علمی برای آن ساخته نمی‌شود.':project.sourceKind==='scenario'?'این طرح از فرصت‌های منتخب برنامه پرتفوی سالانه به تخصیص منتقل شده است.':'این پرونده در فهرست طرح‌های تخصیص سال ثبت شده است.'}</p><dl className="story-entry-facts"><div><dt>مسیر انتخاب</dt><dd>{project.entryMode?ENTRY_MODES[project.entryMode].label:"در نسخه قبلی تعیین نشده"}</dd></div><div><dt>حوزه مادر</dt><dd>{project.parentName||'ثبت نشده'}</dd></div><div><dt>نوع نیاز</dt><dd>{project.needType}</dd></div><div><dt>نیاز کل طرح</dt><dd>{fa(project.totalNeed)}</dd></div><div><dt>شرط اجرا</dt><dd>{project.stageable?`اجرای مرحله‌ای؛ حداقل ${fa(100*project.minimumExecution)}٪ نیاز سال`:'تأمین کامل نیاز سال لازم است'}</dd></div></dl><p className="story-hint">تخصیص به پرونده طرح و سال آن انجام می‌شود. انتخاب حوزه، به‌تنهایی تعهد تأمین مالی نیست.</p></>}
   {event.kind==='turn'&&<><p className="story-lead">این طرح در نوبت <b>{fa(project.audit?.position)}</b> بررسی شد؛ مبنای تقدم: <b>{project.audit?basis[project.audit.priorityBasis]:'در این نسخه ثبت نشده'}</b>. {project.overrideRank?`رتبه مصوب ${fa(project.overrideRank)}.`:project.entryRank?`رتبه ورود ${fa(project.entryRank)}.`:''}</p><div className="story-turn-summary"><Amount label="تأمین نهایی طرح‌های مقدم" value={project.audit?.priorProjects.reduce((n,p)=>n+p.executed,0)}/><Amount label="سقف بدهی قابل استفاده در آغاز نوبت" value={project.audit?.start.remainingDebtCeiling}/></div><details><summary>کدام طرح‌ها پیش از این بررسی شدند؟</summary>{project.audit?.priorProjects.length?<ul className="story-prior-projects">{project.audit.priorProjects.map(p=><li key={p.id}><span>{p.name}</span><b>{fa(p.executed)} میلیارد تومان نهایی</b></li>)}</ul>:<p>{project.audit?'این طرح نخستین نوبت تخصیص را دارد.':'جزئیات نوبت این نسخه ثبت نشده است.'}</p>}</details><p className="story-hint">مبلغ موقتی که در طرح مقدم آزاد شده، مصرف نهایی منابع محسوب نمی‌شود.</p></>}
   {event.kind==='source'&&stage&&decision&&<>
    <p className="story-lead"><b>چرا این منبع؟</b> {decision.why}</p>
    <div className="story-transfer" style={{'--source-color':colors[stage.source!]} as React.CSSProperties}><Amount label="نیاز قبل از این مرحله" value={stage.needBefore}/><ArrowLeft/><Amount label="مبلغ موقت این مرحله" value={stage.allocation} kind="positive"/><ArrowLeft/><Amount label="نیاز پس از این مرحله" value={stage.needAfter} kind="gap"/></div>
    <SourceGraphic stage={stage}/>
    <div className="story-source-controls"><span>ظرفیت پس از کنترل سقف بدهی: <b>{fa(stage.usableCapacity)}</b></span>{FUNDING_SOURCES[stage.source!].debt&&<><span>سقف مشترک بدهی باقی‌مانده: <b>{fa(stage.remainingDebtCeiling)}</b></span><span>نرخ منبع: <b>{fa((stage.rate??0)*100)}٪</b> · سقف طرح: <b>{project.maximumRate==null?'بدون سقف':`${fa(project.maximumRate*100)}٪`}</b></span></>}{decision.limit!=null&&<span>سقف مرحله اختصاصی: <b>{fa(decision.limit)}</b></span>}</div>
    {stage.selectionReason==='custom_order'&&stage.selectionNote&&<p className="story-policy-note">دلیل ثبت‌شده مدیریت برای سیاست منابع: {stage.selectionNote}</p>}
    <div className="story-permissions">{decision.permissions.map(p=><span key={p.label} className={p.pass===false?'blocked':p.pass===true?'allowed':'unknown'}><b>{p.pass===false?'رد':p.pass===true?'مجاز':'ثبت نشده'}</b>{p.label}</span>)}</div>
    <div className="story-amount-rule"><h5>چرا دقیقاً {fa(stage.allocation)} تخصیص موقت یافت؟</h5>{decision.blocked?<p>حداقل یکی از مجوزها یا شرط نرخ رعایت نشده است؛ تخصیص این مرحله صفر شد، حتی اگر ظرفیت وجود داشته باشد.</p>:<><p>پس از عبور از شروط، کمترین مبلغ بین موارد زیر سقف تخصیص این مرحله است:</p><div>{decision.candidates.map(c=><Amount key={c.label} label={c.label} value={c.amount}/>)}</div></>}<p className="story-recorded-result">مبلغ ثبت‌شده موتور: <b>{fa(stage.allocation)}</b> · {stage.note}</p></div>
    {decision.explanations.length>0&&<ul className="story-constraints">{decision.explanations.map((text,i)=><li key={i}>{text}</li>)}</ul>}
    <details className="story-evidence"><summary><CircleHelp size={16}/> ارقام کامل و اثر طرح‌های دیگر</summary><dl className="story-entry-facts"><div><dt>مسیر انتخاب</dt><dd>{project.entryMode?ENTRY_MODES[project.entryMode].label:"در نسخه قبلی تعیین نشده"}</dd></div><div><dt>مانده قبل از کنترل سقف مشترک بدهی</dt><dd>{fa(stage.sourceRemaining)}</dd></div><div><dt>سقف مشترک بدهی باقی‌مانده</dt><dd>{FUNDING_SOURCES[stage.source!].debt?fa(stage.remainingDebtCeiling):'این منبع بدهی نیست'}</dd></div><div><dt>ظرفیت پس از سقف مشترک بدهی</dt><dd>{fa(stage.usableCapacity)}</dd></div><div><dt>نرخ منبع / سقف نرخ طرح</dt><dd>{stage.rate==null?'بدون نرخ بدهی':`${fa(stage.rate*100)}٪`} / {project.maximumRate==null?'بدون سقف':`${fa(project.maximumRate*100)}٪`}</dd></div><div><dt>سقف مرحله اختصاصی</dt><dd>{decision.limit==null?'بدون سقف اختصاصی':fa(decision.limit)}</dd></div></dl>{stage.consumers?.length?<p>مصرف نهایی این منبع در طرح‌های مقدم: {holders(stage.consumers)}</p>:null}{stage.reservationHolders?.length?<p>رزرو این منبع برای: {holders(stage.reservationHolders)}</p>:null}{stage.debtConsumers?.length?<p>مصرف سقف مشترک بدهی: {holders(stage.debtConsumers)}</p>:null}{stage.debtReservationHolders?.length?<p>رزرو سقف مشترک بدهی: {holders(stage.debtReservationHolders)}</p>:null}<p>این مبلغ هنوز موقت است؛ پس از بررسی منابع، حداقل اجرای کل طرح کنترل می‌شود.</p></details>
   </>}
   {event.kind==='unneeded'&&<><p className="story-lead">نیاز باقی‌مانده به صفر رسید؛ مراجعه‌های زیر دیگر به تخصیص بیشتر نیاز نداشتند.</p><ul className="story-skipped">{event.unneeded?.map(t=><li key={t.index}>{FUNDING_SOURCES[t.source].label} · {t.stage} <b>نیازی نبود</b></li>)}</ul><p className="story-hint">این وضعیت به معنای نداشتن ظرفیت یا نامجاز بودن منابع نیست.</p></>}
   {event.kind==='gate'&&<><div className="story-gate-graphic"><Amount label="جمع تأمین موقت" value={review.temporary}/><span className={project.passedMinimum?'passed':'failed'}>{project.passedMinimum?'حداقل تأمین شد':'به حداقل نرسید'}</span><Amount label="حداقل لازم برای اجرا" value={project.minimumRequired}/></div><p className="story-lead">{project.passedMinimum?`مبلغ موقت ${fa(review.temporary)} از حداقل لازم کمتر نیست؛ ${fa(project.executed)} به تخصیص نهایی تبدیل شد.`:`مبلغ موقت ${fa(review.temporary)} به حداقل ${fa(project.minimumRequired)} نرسید؛ ${fa(review.released)} آزاد شد و تأمین نهایی صفر است.`}</p>{(project.audit?.end.ownReservation??0)>0&&<p className="story-hint">رزرو مصرف‌نشده همین طرح: {fa(project.audit?.end.ownReservation)}؛ این تعهد هنوز برای طرح محفوظ است و ظرفیت آزاد دیگران نیست.</p>}</>}
   {event.kind==='stop'&&<><p className="story-lead">{project.reason}</p><p className="story-hint">توقف پیش از بررسی منابع؛ صفر تخصیص، به معنای صفر بودن ظرفیت منابع نیست.</p>{action.run&&<button className="story-primary" onClick={action.run}>{action.label}</button>}</>}
   {event.kind==='result'&&<><div className={`story-result-status ${project.executed>0?'passed':'failed'}`}><b>{project.decision}</b>{project.validation.valid&&<span>پوشش نیاز: {fa(100*project.executed/Math.max(.01,project.annualNeed))}٪</span>}</div><p className="story-lead">{review.narrative}</p>{review.assessed&&<><div className="story-final-bar" role="img" aria-label={`تأمین نهایی ${fa(project.executed)} و کسری ${fa(project.deferred)}`}>{review.rows.filter(r=>r.amount>0).map(r=><i key={r.key} style={{background:colors[r.key],width:`${100*r.amount/Math.max(.01,project.annualNeed)}%`}}/>)}<i className="story-final-gap" style={{width:`${100*project.deferred/Math.max(.01,project.annualNeed)}%`}}/></div><div className="story-final-sources">{review.rows.filter(r=>r.amount>0||r.released>0).map(r=><article key={r.key} style={{borderInlineStartColor:colors[r.key]}}><b>{r.label}</b><span>نهایی <strong>{fa(r.amount)}</strong></span>{r.released>0&&<small>آزادشده {fa(r.released)}</small>}</article>)}</div><p className="story-hint">تأمین نهایی {fa(project.executed)} + کسری {fa(project.deferred)} = نیاز {fa(project.annualNeed)} میلیارد تومان.</p></>}{!project.validation.valid&&<p className="story-hint">نیاز و کسری تا تکمیل پرونده قابل اتکا نیست.</p>}{action.run&&<button className="story-primary" onClick={action.run}>{action.label}</button>}</>}
  </section>
  <nav className="story-navigation" aria-label="حرکت در مسیر همین طرح"><button disabled={index===0} onClick={()=>setPosition(index-1)}><ArrowRight size={16}/> قبلی</button><span>نمایش محاسبات ثبت‌شده · جابه‌جایی مراحل مبلغی را تغییر نمی‌دهد</span><button className="story-primary" disabled={index===events.length-1} onClick={()=>setPosition(index+1)}>بعدی <ArrowLeft size={16}/></button></nav>
 </section>;
}
