"use client";
import {useState} from 'react';
import {findFundingImprovement,type FundingSearch} from '@/lib/funding-improvement.mjs';
import {FUNDING_SOURCES,type allocateCapital,type SourcePolicy} from '@/lib/capital-allocation.mjs';
const fa=(n:number)=>n.toLocaleString('fa-IR',{maximumFractionDigits:2});
export default function FundingImprovement({input,onApply,otherYears=[]}:{otherYears?:Parameters<typeof allocateCapital>[0][];input:Parameters<typeof allocateCapital>[0];onApply:(policy:SourcePolicy)=>void}){
 const signature=JSON.stringify([input,otherYears]);const [result,setResult]=useState<{signature:string;value:FundingSearch}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const current=result?.signature===signature?result.value:null;
 function run(){setBusy(true);setError('');setTimeout(()=>{try{setResult({signature,value:findFundingImprovement(input,undefined,otherYears)});}catch{setError('بررسی انجام نشد؛ اعتبار ورودی و سیاست منابع را بررسی کنید.');}finally{setBusy(false);}},20);}
 return <section className="funding-improvement"><header><div><h3>با همین منابع، امکان تأمین بیشتری داریم؟</h3><p>ترتیب منابع بررسی می‌شود؛ مبلغ تأمین هیچ طرح در سال جاری و سایر سال‌های همین سبد نسبت به نتیجه جاری کاهش نمی‌یابد.</p></div><button disabled={busy} onClick={run}>{busy?'در حال بررسی…':'بررسی امکان تأمین بهتر'}</button></header>{error&&<p role="alert">{error}</p>}{current&&<><p role="status">{current.status==='improved'?`با تغییر ترتیب منابع، ${fa(current.gain)} میلیارد تومان تأمین بیشتر یافت شد.`:current.status==='blocked'?'ابتدا موانع و ورودی‌های نامعتبر را رفع کنید.':'در ترتیب‌های بررسی‌شده، بهبود بدون کاهش تأمین طرح‌های فعلی پیدا نشد؛ این نتیجه اثبات بهینه‌بودن کل سبد نیست.'}</p>{current.best&&<><div className="funding-comparison"><b>تأمین جاری: {fa(current.baseline.totalExecuted)}</b><b>تأمین پیشنهادی: {fa(current.best.totalExecuted)}</b><span>میلیارد تومان</span></div>{current.changes.map(c=><p key={c.needType}><b>{c.needType}</b><br/>جاری: {c.before.map(s=>FUNDING_SOURCES[s].label).join(' ← ')}<br/>پیشنهاد: {c.after.map(s=>FUNDING_SOURCES[s].label).join(' ← ')}</p>)}<div className="table-scroll"><table><thead><tr><th>طرح</th><th>تأمین جاری</th><th>تأمین پیشنهادی</th><th>تغییر</th></tr></thead><tbody>{current.baseline.results.map(r=>{const n=current.best!.results.find(p=>p.id===r.id)!;return <tr key={r.id}><td>{r.name}</td><td>{fa(r.executed)}</td><td>{fa(n.executed)}</td><td>{fa(n.executed-r.executed)}</td></tr>;})}</tbody></table></div><button onClick={()=>onApply({...current.policy,reason:[input.sourcePolicy?.reason,'اعمال پیشنهاد بررسی ترتیب منابع؛ حفظ حداقل تأمین جاری همه طرح‌ها'].filter(Boolean).join('؛ ')})}>اعمال ترتیب پیشنهادی و محاسبه مجدد</button></>}<small>{fa(current.tested)} ترتیب بررسی شد. این بررسی محدودِ سیاست منابع است؛ کمینه‌سازی هزینه، تغییر رتبه طرح‌ها و تضمین بهترین جواب جهانی انجام نمی‌دهد.</small></>}</section>;
}
