"use client";
import { useState, type ComponentType } from "react";
import { Layers3, BriefcaseBusiness, ChartNoAxesCombined, Wallet, Building2 } from "lucide-react";
import { ParentingBadge } from "./company-narratives";
import data from "@/public/data/portfolio-book-1404.json";

type Company = typeof data.companies[number];
type Segment = {label:string;value:number;color:string};
type Props = {portfolio:{name:string;control:string;horizon:string}[];Donut:ComponentType<{title:string;note:string;segments:Segment[];centerLabel?:string}>};
const fa=(n:number,d=2)=>n.toLocaleString("fa-IR",{minimumFractionDigits:d,maximumFractionDigits:d});
// Source amounts are million IRR: /10,000 => billion toman; /10,000,000 => trillion toman (همت).
const billion=(n:number)=>fa(n/10_000);
const trillion=(n:number)=>fa(n/10_000_000);
const rows=data.companies;
const sum=(key:"equity"|"attributedEquity"|"profit"|"attributedProfit")=>rows.reduce((s,c)=>s+c[key],0);
const totals={equity:sum("equity"),attributedEquity:sum("attributedEquity"),profit:sum("profit"),attributedProfit:sum("attributedProfit")};
const colors=["#075cab","#d4a14d","#39866e","#7654a7"];
export default function PortfolioOverview({portfolio,Donut}:Props){
 const [scope,setScope]=useState<"all"|"atieh">("atieh");
 const [metric,setMetric]=useState<"equity"|"profit">("equity");
 const [filter,setFilter]=useState("all");
 const [sort,setSort]=useState<"attributedEquity"|"attributedProfit"|"ownershipPercent">("attributedEquity");
 const [descending,setDescending]=useState(true);
 const value=(c:Company)=>metric==="equity"?(scope==="all"?c.equity:c.attributedEquity):(scope==="all"?c.profit:c.attributedProfit);
 const classification=(c:Company)=>portfolio.find(p=>p.name===c.name);
 const aggregate=(label:(c:Company)=>string):Segment[]=>Object.entries(rows.reduce((m,c)=>{const k=label(c);m[k]=(m[k]??0)+value(c);return m;},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]).map(([label,value],i)=>({label,value,color:colors[i%colors.length]}));
 const visible=rows.filter(c=>filter==="all"||c.parenting===filter).sort((a,b)=>(descending?-1:1)*(a[sort]-b[sort]));
 const ranked=[...rows].sort((a,b)=>b.attributedEquity-a.attributedEquity);
 const metil=rows.find(c=>c.name==="فولاد متیل")!;
 const card=(kind:"equity"|"profit",title:string,shareTitle:string)=>{
  const total=totals[kind],share=kind==="equity"?totals.attributedEquity:totals.attributedProfit,percent=share/total*100;
  return <article className={`portfolio-value-card ${kind}`}><header>{kind==="equity"?<Wallet/>:<ChartNoAxesCombined/>}<span>{title}</span><small>۱۴۰۴</small></header><div className="portfolio-total-number">{trillion(total)} <small>همت تومان</small></div><div className="portfolio-atieh-number"><span>{shareTitle}</span><strong>{trillion(share)} <small>همت تومان</small></strong></div><div className="portfolio-participation-bar" role="img" aria-label={`سهم آتیه ${fa(percent,1)} درصد`}><i style={{width:`${percent}%`}}/></div><div className="portfolio-participation-legend"><span><i/>آتیه {fa(percent,1)}٪</span><span>سایر سهامداران {fa(100-percent,1)}٪</span></div><footer>{kind==="equity"?"مجموع حقوق مالکانه شرکت‌ها؛ ارزش دفتری، نه ارزش روز":"سود خالص عملیات در حال تداوم؛ سهم سود به معنی سود نقدی دریافتی نیست"}</footer></article>;
 };
 return <div className="content-stack portfolio-book-overview">
  <div className="portfolio-book-heading"><span><Building2 size={18}/> تصویر پرتفوی در پایان ۱۴۰۴</span><small>۱۰ شرکت · مبالغ اصلی: میلیون ریال</small></div>
  <section className="portfolio-value-grid">{card("equity","ارزش دفتری کل پرتفوی","سهم آتیه از ارزش دفتری")}{card("profit","سود خالص کل شرکت‌های پرتفوی","سهم آتیه از سود خالص")}</section>
  <section className="panel portfolio-lenses"><div className="section-title"><span><Layers3/></span><div><h2>ترکیب پرتفوی از دو نگاه</h2><p>مبنای نمایش: {scope==="all"?"کل شرکت‌ها، بدون اعمال درصد مالکیت":"سهم آتیه، بر اساس مبالغ منتسب جدول"} · {metric==="equity"?"حقوق مالکانه":"سود خالص"}</p></div></div><div className="portfolio-lens-controls"><div role="group" aria-label="دامنه نمایش"><button aria-pressed={scope==="all"} onClick={()=>setScope("all")}>کل شرکت‌ها</button><button aria-pressed={scope==="atieh"} onClick={()=>setScope("atieh")}>سهم آتیه</button></div><div role="group" aria-label="مبنای نمودار"><button aria-pressed={metric==="equity"} onClick={()=>setMetric("equity")}>ارزش دفتری</button><button aria-pressed={metric==="profit"} onClick={()=>setMetric("profit")}>سود خالص</button></div></div><div className="composition-grid"><Donut title="ترکیب بر مبنای ماهیت" note="طبقه‌بندی جدول سال ۱۴۰۴" segments={aggregate(c=>c.nature)}/><Donut title="ساختار کنترل" note="طبقه‌بندی کنترلی موجود در نرم‌افزار" segments={aggregate(c=>classification(c)?.control??"تعیین‌نشده")}/><Donut title="هسته و مجاور" note="بازرگانی/خدماتی: هسته؛ سایر فعالیت‌ها: مجاور" segments={aggregate(c=>c.nature==="بازرگانی/خدماتی"?"هسته؛ بازرگانی/خدماتی":"کسب‌وکارهای مجاور")}/></div></section>
  <section className="panel portfolio-contribution"><div className="section-title"><span><ChartNoAxesCombined/></span><div><h2>وزن شرکت‌ها و نقش آن‌ها در سود آتیه</h2><p>درصد هر شرکت از مجموع ارزش دفتری و مجموع سود منتسب به آتیه</p></div></div><div className="portfolio-chart-key"><span><i/> سهم از ارزش دفتری</span><span><i/> سهم از سود</span></div><div className="portfolio-contribution-rows">{ranked.map(c=><div className="portfolio-contribution-row" key={c.name}><strong>{c.name}</strong><div>{(["attributedEquity","attributedProfit"] as const).map((key,i)=>{const percent=c[key]/totals[key]*100;return <div className={`portfolio-bar-line ${i?"profit":"equity"}`} key={key}><div><i style={{width:`${percent}%`}}/></div><b>{fa(percent,1)}٪</b></div>;})}</div></div>)}</div><div className="portfolio-at-a-glance"><strong>پرتفوی در یک نگاه</strong><p>متیل {fa(metil.attributedEquity/totals.attributedEquity*100,1)}٪ از ارزش دفتری سهم آتیه و {fa(metil.attributedProfit/totals.attributedProfit*100,1)}٪ از سهم سود آتیه را تشکیل می‌دهد.</p></div></section>
  <section className="panel ownership-panel"><div className="section-title"><span><BriefcaseBusiness/></span><div><h2>ارزش، سود و استراتژی سرپرستی شرکت‌ها</h2><p>تمام مبالغ جدول: میلیارد تومان · درصدهای مالکیت مطابق جدول شما و گرد شده‌اند</p></div></div><div className="portfolio-table-controls"><label>سرپرستی<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">همه شرکت‌ها</option><option value="financial">کنترل مالی</option><option value="strategic">کنترل راهبردی</option></select></label><label>مرتب‌سازی<select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="attributedEquity">ارزش دفتری سهم آتیه</option><option value="attributedProfit">سهم سود آتیه</option><option value="ownershipPercent">درصد مالکیت</option></select></label><button onClick={()=>setDescending(!descending)}>{descending?"بیشترین به کمترین ↓":"کمترین به بیشترین ↑"}</button><small>{fa(visible.length,0)} شرکت</small></div><div className="ownership-table-wrap portfolio-book-table"><table><thead><tr><th>شرکت / ماهیت</th><th>مالکیت آتیه</th><th>حقوق مالکانه کل</th><th>ارزش دفتری سهم آتیه</th><th>وزن در ارزش آتیه</th><th>سود خالص کل</th><th>سهم سود آتیه</th><th>وزن در سود آتیه</th><th>استراتژی سرپرستی</th></tr></thead><tbody>{visible.map(c=><tr key={c.name}><td><b>{c.name}</b><small>{c.nature}</small></td><td>{fa(c.ownershipPercent,0)}٪</td><td>{billion(c.equity)}</td><td className="portfolio-equity-cell">{billion(c.attributedEquity)}</td><td>{fa(c.attributedEquity/totals.attributedEquity*100,1)}٪</td><td>{billion(c.profit)}</td><td className="portfolio-profit-cell">{billion(c.attributedProfit)}</td><td>{fa(c.attributedProfit/totals.attributedProfit*100,1)}٪</td><td><ParentingBadge name={c.name} compact/></td></tr>)}</tbody><tfoot><tr><th>{filter==="all"?"جمع کل پرتفوی":"جمع شرکت‌های فیلترشده"}</th><td>—</td>{(["equity","attributedEquity"] as const).map(k=><td key={k}>{billion(visible.reduce((s,c)=>s+c[k],0))}</td>)}<td>{fa(visible.reduce((s,c)=>s+c.attributedEquity,0)/totals.attributedEquity*100,1)}٪</td>{(["profit","attributedProfit"] as const).map(k=><td key={k}>{billion(visible.reduce((s,c)=>s+c[k],0))}</td>)}<td>{fa(visible.reduce((s,c)=>s+c.attributedProfit,0)/totals.attributedProfit*100,1)}٪</td><td>—</td></tr></tfoot></table></div><p className="portfolio-source-note">مبالغ سهم آتیه عیناً از ستون‌های سهم جدول مدیریت خوانده شده‌اند و با درصدهای گرد‌شده دوباره محاسبه نمی‌شوند. وزن‌های جدول همیشه نسبت به کل پرتفوی آتیه هستند. مجموع‌ها جمع همین ۱۰ شرکت‌اند و جایگزین صورت مالی تلفیقی هلدینگ نیستند.</p></section>
 </div>;
}
