"use client";
import {useState} from "react";
import {allocateCapital,type CapitalProject} from "@/lib/capital-allocation.mjs";
import {scopedCases} from "@/lib/scenario-workspace.mjs";
type Project=CapitalProject & {opportunityKey?:string;sourceKind?:string;runKey?:string};
const fundingPolicyOnly=(policy?:import("@/lib/capital-allocation.mjs").SourcePolicy)=>{const funding={...(policy??{})};delete funding.liquidityMode;delete funding.liquidityReason;delete funding.liquiditySources;return funding;};
export default function ScenarioCapitalComparison({snapshots,year,cases,financial,actions,sourcePolicies,liquidityPoliciesByYear}:{snapshots:{id:string;name:string;revision:number;plans:{year:number;key:string}[]}[];year:number;cases:Record<string,Project>;financial:Record<string,number>;sourcePolicies?:Record<string,import("@/lib/capital-allocation.mjs").SourcePolicy>;liquidityPoliciesByYear?:Record<string,import("@/lib/capital-allocation.mjs").SourcePolicy>;actions:{action:string;year:number;reliableProceeds:number;status:string}[]}) {
 const [open,setOpen]=useState(false);
 const fa=(n:number)=>n.toLocaleString("fa-IR",{maximumFractionDigits:0});
 return <details className="scenario-capital-comparison" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>مقایسه وضعیت تأمین سناریوها در سال {year.toLocaleString("fa-IR",{useGrouping:false})}</summary><p>هر سناریو جدا با ظرفیت مالی یکسان ارزیابی می‌شود. پروژه مستقل در هر ارزیابی حضور دارد. این مقایسه، تجمیع منابع یا انتخاب خودکار سناریو نیست.</p><div className="table-scroll"><table><thead><tr><th>سناریو</th><th>پرونده سال</th><th>نیاز سرمایه</th><th>تأمین‌شده</th><th>شکاف</th><th>ظرفیت باقی‌مانده</th><th>کیفیت ورودی پرونده</th></tr></thead><tbody>{open&&snapshots.map(s=>{const projects=Object.values(scopedCases(cases,s.id));const o=allocateCapital({year,financialInput:financial,portfolioActions:actions,projects,sourcePolicy:{liquidityMode:"block",...fundingPolicyOnly(sourcePolicies?.[s.id]),...liquidityPoliciesByYear?.[`${s.id}:${year}`]}});const missing=s.plans.filter(p=>p.year===year&&!projects.some(c=>c.year===year&&c.opportunityKey===p.key)).length;const incomplete=missing>0||!o.financialValidation.valid||!o.results.length||o.results.some(r=>!r.validation.valid);return <tr key={s.id}><td>{s.name} · نسخه {fa(s.revision)}</td><td>{fa(o.results.length)}</td><td>{incomplete?"نیاز نامشخص":fa(o.totalNeed)}</td><td>{fa(o.totalExecuted)}</td><td>{incomplete?"قابل جمع‌بندی نیست":fa(o.totalDeferred)}</td><td>{fa(o.freeCapacity)}</td><td>{!o.financialValidation.valid?"ورودی مالی ناقص":missing?`${fa(missing)} انتخاب سناریو فاقد پرونده`:!o.results.length?"پرونده سال ثبت نشده":o.results.some(r=>!r.validation.valid)?"نیازمند تکمیل":!o.policyValid?"سیاست تأمین ناقص":o.liquidityBlocked?"کسری نقد؛ اجرای جدید متوقف":o.reservationConflict?"تعارض منابع رزروشده":"ورودی معتبر"}</td></tr>;})}</tbody></table></div><small>مبالغ: میلیارد تومان. تا تأیید ورودی مالی، نتایج پیش‌نمایش‌اند. پرونده سبد مشترک در ارزیابی مستقل هر سناریو وارد نمی‌شود.</small></details>;
}
