"use client";
import { useState } from "react";
import { Copy, GitCompareArrows, Plus, Send, ShieldCheck, Download, Upload, FolderCog, Trash2, RotateCcw } from "lucide-react";

type Scenario = {id:string;name:string;completed:string[];revision:number;updatedAt?:string;base:{vision:Record<string,number>;baskets:Record<number,Record<string,{share:number;priorityRank?:number}>>;board:Record<number,{score:number|null}>}};
export default function ScenarioControls({scenarios,activeId,onSelect,onCreate,onFreeze,snapshots,saveStatus,lastSavedAt,lastBackupAt,archivedIds=[],onArchive,onRename,onExport,onBackup,onImport,onOpenCapital}:{saveStatus?:string;lastSavedAt?:string|null;lastBackupAt?:string|null;archivedIds?:string[];onArchive:(id:string,archived:boolean)=>void;onRename:(id:string,name:string)=>void;onExport:(id:string)=>void;onBackup:()=>void;onImport:()=>void;onOpenCapital:()=>void;scenarios:Scenario[];activeId:string;onSelect:(id:string)=>void;onCreate:(name:string,duplicate:boolean)=>void;onFreeze:()=>void;snapshots:{scenarioId:string;name:string;revision?:number;plans:{year:number;share:number;priorityRank?:number;entryPriority:number}[]}[]}) {
  const [name,setName]=useState(""); const [compare,setCompare]=useState(false);
  const [error,setError]=useState(""); const [manage,setManage]=useState(false); const [pendingDelete,setPendingDelete]=useState<string|null>(null); const [renameId,setRenameId]=useState<string|null>(null); const [newName,setNewName]=useState("");
  const [archiveTab,setArchiveTab]=useState(false);
  const [search,setSearch]=useState("");
  const formatTime=(date?:string|null)=>date?new Date(date).toLocaleString("fa-IR",{timeZone:"Asia/Tehran",dateStyle:"short",timeStyle:"short"}):"هنوز ثبت نشده";
  const statusOf=(s:Scenario)=>{const outputs=snapshots.filter(x=>x.scenarioId===s.id);return !outputs.length?(s.completed.length===4?"آماده انتقال":"در حال تکمیل"):s.revision>Math.max(...outputs.map(x=>x.revision??0))?"اصلاح‌شده پس از انتقال":"منتقل‌شده به تخصیص سرمایه";};
  const active=scenarios.find(s=>s.id===activeId);
  const live=scenarios.filter(s=>!archivedIds.includes(s.id));
  const create=(duplicate:boolean)=>{const clean=name.trim();if(!clean){setError("نام سناریو را وارد کنید.");return;}if(live.some(s=>s.name===clean)){setError("برای سناریوی جدید نام متفاوتی انتخاب کنید.");return;}onCreate(clean,duplicate);setName("");setError("");};
  return <section className="scenario-workbench scenario-workbench-enhanced">
    <header><div><span>تصمیم‌های مستقل، مسیرهای قابل مقایسه</span><h2>مرکز مدیریت سناریوها</h2></div><span className="scenario-autosave"><ShieldCheck/> {saveStatus??"ذخیره خودکار در این مرورگر"}<small>{formatTime(lastSavedAt)}</small></span></header>
    {active&&<div className="scenario-active-banner"><div><span>سناریوی فعال</span><h3>{active.name}</h3><p>{statusOf(active)}</p></div><div className="scenario-step-dots" aria-label="پیشرفت بررسی">{[1,2,3,4].map(i=><span key={i} className={i<=active.completed.length?"done":""}>{i.toLocaleString("fa-IR")}</span>)}</div></div>}
    <div className="scenario-file-actions"><button onClick={onBackup}><Download/> دانلود پشتیبان کامل</button><button onClick={onImport}><Upload/> بازیابی از فایل</button><button onClick={()=>setManage(!manage)} aria-expanded={manage}><FolderCog/> مدیریت سناریوها</button></div>
    <p className="scenario-storage-note">اطلاعات فقط در همین مرورگر نگهداری می‌شود، نه روی سرور. آخرین درخواست دانلود در این نشست: {formatTime(lastBackupAt)}</p>
    <div className="scenario-toolbar">
      <label><span>سناریوی جاری</span><select aria-label="سناریوی جاری" value={activeId} onChange={e=>onSelect(e.target.value)}><option value="" disabled>انتخاب سناریو</option>{live.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label><span>نام سناریوی جدید</span><input aria-label="نام سناریوی جدید" value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً رشد گزینشی زنجیره فولاد" maxLength={100}/></label>
      <button onClick={()=>create(false)}><Plus/> سناریوی جدید</button><button disabled={!activeId} onClick={()=>create(true)}><Copy/> کپی سناریوی جاری</button><button disabled={!scenarios.length} onClick={()=>setCompare(!compare)}><GitCompareArrows/> مقایسه</button>
    </div>{error&&<p role="alert">{error}</p>}
    {activeId&&<div className="scenario-progress"><span>{scenarios.find(s=>s.id===activeId)?.completed.length.toLocaleString("fa-IR")} از ۴ مرحله تأیید شده</span><button onClick={onFreeze}><Send/> بررسی برنامه نهایی</button><small>خروجی ثابت می‌ماند؛ اصلاح بعدی با نسخه تازه منتقل می‌شود.</small></div>}
    {manage&&<div className="scenario-manager"><header><h3>فهرست سناریوها</h3><div className="scenario-manager-filters"><button className={!archiveTab?"active":""} onClick={()=>setArchiveTab(false)}>فعال‌ها · {live.length.toLocaleString("fa-IR")}</button><button className={archiveTab?"active":""} onClick={()=>setArchiveTab(true)}>بایگانی · {archivedIds.length.toLocaleString("fa-IR")}</button><input aria-label="جست‌وجوی سناریو" placeholder="جست‌وجوی نام سناریو…" value={search} onChange={e=>setSearch(e.target.value)}/></div><p>هر سناریو یک تصمیم مستقل است. بایگانی، آن را از فهرست فعال و تخصیص سرمایه کنار می‌گذارد؛ اطلاعات برای بازگردانی حفظ می‌شوند.</p></header><div className="table-scroll"><table><thead><tr><th>سناریو</th><th>وضعیت بررسی</th><th>خروجی تخصیص سرمایه</th><th>مدیریت</th></tr></thead><tbody>{scenarios.filter(s=>archivedIds.includes(s.id)===archiveTab&&s.name.includes(search.trim())).map(s=>{const removed=archivedIds.includes(s.id);const outputs=snapshots.filter(x=>x.scenarioId===s.id);return <tr key={s.id} className={removed?"scenario-removed":s.id===activeId?"scenario-current":""}><td>{renameId===s.id?<form onSubmit={e=>{e.preventDefault();try{onRename(s.id,newName);setRenameId(null);setError("");}catch(e){setError(e instanceof Error?e.message:"نام معتبر نیست.");}}}><input aria-label={`نام جدید ${s.name}`} value={newName} onChange={e=>setNewName(e.target.value)} maxLength={100}/><button type="submit">ثبت نام</button><button type="button" onClick={()=>setRenameId(null)}>انصراف</button></form>:<><b>{s.name}</b><small>نسخه {s.revision.toLocaleString("fa-IR")} · {removed?"بایگانی‌شده؛ قابل بازگردانی":s.id===activeId?"سناریوی جاری":"آماده انتخاب"}</small></>}</td><td><span className="scenario-status-label">{statusOf(s)}</span><small>{s.completed.length.toLocaleString("fa-IR")} از ۴ مرحله</small><small>آخرین تغییر: {formatTime(s.updatedAt)}</small></td><td>{outputs.length?`${outputs.length.toLocaleString("fa-IR")} خروجی ثبت‌شده`:"هنوز منتقل نشده"}<small>اصلاح سناریو، خروجی قبلی را تغییر نمی‌دهد.</small></td><td><div className="scenario-row-actions">{removed?<button onClick={()=>onArchive(s.id,false)}><RotateCcw/> بازگردانی</button>:<><button onClick={()=>onSelect(s.id)}>انتخاب</button><button onClick={()=>{setRenameId(s.id);setNewName(s.name);}}>تغییر نام</button><button onClick={()=>setPendingDelete(s.id)}><Trash2/> بایگانی</button></>}<button onClick={()=>onExport(s.id)}><Download/> دانلود این سناریو</button></div>{pendingDelete===s.id&&<div className="scenario-delete-confirm"><span>«{s.name}» از سناریوهای فعال و سبد تخصیص کنار گذاشته شود؟</span><button onClick={()=>{onArchive(s.id,true);setPendingDelete(null);}}>تأیید بایگانی</button><button onClick={()=>setPendingDelete(null)}>انصراف</button></div>}</td></tr>})}</tbody></table></div>{!scenarios.length&&<p>هنوز سناریویی ثبت نشده است.</p>}</div>}
    {activeId&&snapshots.some(s=>s.scenarioId===activeId)&&<div className="scenario-transfer-status"><ShieldCheck/><div><b>{active?statusOf(active):"خروجی ثبت‌شده موجود است"}</b><span>برای انتقال اصلاحات، چهار مرحله نسخه جدید را تأیید کنید. خروجی قبلی تا آن زمان محفوظ است.</span></div><button onClick={onOpenCapital}>مشاهده در تخصیص سرمایه</button></div>}
    {compare&&<div className="scenario-comparison"><p>مقایسه سیاست‌ها و انتخاب‌ها؛ هیچ امتیاز علمی تازه‌ای ساخته نمی‌شود.</p><div className="table-scroll"><table><thead><tr><th>سناریو</th><th>هسته / مجاور / تحولی</th><th>حوزه‌های دارای نظر مدیریت</th><th>انتخاب‌های سالانه</th><th>سال‌های دارای برنامه</th><th>پیشرفت بررسی</th></tr></thead><tbody>{live.map(s=>{const years=Object.entries(s.base.baskets).filter(([,b])=>Object.values(b).some(p=>(p.priorityRank??0)>0||p.share>0));return <tr key={s.id}><td><button onClick={()=>onSelect(s.id)}>{s.name}</button></td><td>{["core","adjacent","transform"].map(k=>(s.base.vision[k]).toLocaleString("fa-IR",{maximumFractionDigits:1})).join(" / ")}٪</td><td>{Object.values(s.base.board).filter(b=>b.score!=null).length.toLocaleString("fa-IR")}</td><td>{years.reduce((n,[,b])=>n+Object.values(b).filter(p=>(p.priorityRank??0)>0||p.share>0).length,0).toLocaleString("fa-IR")}</td><td>{years.map(([y])=>Number(y).toLocaleString("fa-IR",{useGrouping:false})).join("، ")||"—"}</td><td>{s.completed.length.toLocaleString("fa-IR")} از ۴</td></tr>;})}</tbody></table></div>
      {snapshots.length>0&&<details><summary>مقایسه خروجی‌های ثبت‌شده</summary><div className="table-scroll"><table><thead><tr><th>خروجی</th><th>سال</th><th>تعداد انتخاب</th><th>مبنای برنامه ورود</th><th>میانگین اولویت ورود منتخب</th></tr></thead><tbody>{snapshots.flatMap((s,i)=>[...new Set(s.plans.map(p=>p.year))].map(year=>{const p=s.plans.filter(p=>p.year===year);return <tr key={`${i}:${year}`}><td>{s.name}</td><td>{year.toLocaleString("fa-IR",{useGrouping:false})}</td><td>{p.length.toLocaleString("fa-IR")}</td><td>{p.some(p=>p.priorityRank)?"رتبه‌بندی ورود":`سهم تاریخی ${p.reduce((n,p)=>n+p.share,0).toLocaleString("fa-IR")}٪`}</td><td>{(p.reduce((n,p)=>n+p.entryPriority,0)/p.length).toLocaleString("fa-IR",{maximumFractionDigits:1})}</td></tr>;}))}</tbody></table></div></details>}
    </div>}
  </section>;
}
