"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, Building2, ChevronLeft, Factory, Layers3, Sparkles } from "lucide-react";
import { STEEL_CHAIN_DATA, type SteelNode } from "@/lib/steel-chain-data";

import companyLinks from "@/public/data/market-company-links.json";
const normalizeProduct=(s:string)=>s.replace(/[‌\s–-]/g,"");
const relatedCompanies=(scope:string,product?:string)=>[...new Set(companyLinks.records.filter(row=>row.scope===scope&&(!product||normalizeProduct(row.product)===normalizeProduct(product))).flatMap(row=>row.companies))];

type Topic = "group" | "company" | "future" | "national" | "slab" | "hot" | "trade";
const topics: { id: Topic; label: string; options: { id: string; label: string }[] }[] = [
  { id: "group", label: "نمای کلی گروه فولاد مبارکه", options: [{ id: "all", label: "همه حلقه‌ها" }, { id: "upstream", label: "بالادست" }, { id: "downstream", label: "پایین‌دست" }] },
  { id: "company", label: "شرکت اصلی فولاد مبارکه", options: [{ id: "1405", label: "مقایسه ۱۴۰۴ و ۱۴۰۵" }] },
  { id: "future", label: "سناریو آتی گروه فولاد مبارکه", options: [{ id: "18", label: "تولید ۱۸ میلیون تن فولاد میانی" }, { id: "utilization", label: "نرخ بهره‌وری فعلی" }, { id: "downstream", label: "بازار اسلب و ورق گرم" }] },
  { id: "national", label: "موازنه آتی زنجیره بالادستی فولاد کشور", options: [{ id: "nominal", label: "ظرفیت اسمی" }, { id: "energy", label: "محدودیت انرژی" }, { id: "ore", label: "محدودیت عرضه سنگ‌آهن" }, { id: "likely", label: "سناریوی محتمل" }] },
  { id: "slab", label: "بازار اسلب", options: [{ id: "nominal", label: "ظرفیت اسمی تولید" }, { id: "demand", label: "پیش‌بینی تقاضای بازار" }] },
  { id: "hot", label: "بازار کلاف گرم", options: [{ id: "market", label: "پیش‌بینی تقاضای بازار" }] },
  { id: "trade", label: "روند تجارت و صادرات", options: STEEL_CHAIN_DATA.trade.series.map((item) => ({ id: item.product, label: item.product })) },
];

const num = (v: number | null | undefined, digits = 2) => v == null ? "—" : v.toLocaleString("fa-IR", { maximumFractionDigits: digits, minimumFractionDigits: digits });
const balanceText = (balance: number | null | undefined) => balance == null ? "داده موازنه برای این حلقه ثبت نشده است." : balance > 0 ? "مازاد عرضه" : balance < 0 ? "کسری عرضه" : "تعادل عرضه و تقاضا";

function BalanceBadge({ value }: { value: number | null | undefined }) { return <span className={`steel-balance ${value == null ? "neutral" : value >= 0 ? "positive" : "negative"}`}>{value == null ? "—" : `${value > 0 ? "+" : ""}${num(value)}`} <small>{balanceText(value)}</small></span>; }

function Message({ title = "پیام مدیریتی", children, companies = [] }: { title?: string; children: React.ReactNode; companies?: readonly string[] }) { return <aside className="steel-message"><div><span><Sparkles /></span><small>{title}</small></div><p>{children}</p>{companies.length > 0 && <div className="steel-companies"><Building2 />{companies.map((item) => <b key={item}>{item}</b>)}</div>}</aside>; }

function ChartLegend(){return <div className="steel-chart-legend"><span><i className="supply"/>عرضه / تولید</span><span><i className="demand"/>تقاضا / خودمصرفی</span><span><i className="surplus"/>مازاد</span><span><i className="shortage"/>کسری</span></div>}

function SupplyDemand({ nodes }: { nodes: readonly SteelNode[] }) {
  const max=Math.max(...nodes.flatMap(node=>[node.supply??0,node.demand??0]),1);
  return <section className="steel-balance-board"><header><div><small>مقایسه مستقیم حلقه‌های زنجیره</small><h3>عرضه، تقاضا و موازنه بازار</h3></div><ChartLegend/></header><div className="steel-cluster-chart">{nodes.map((node,index)=><article key={node.product} style={{"--delay":`${index*65}ms`} as React.CSSProperties}><div className="cluster-bars"><div className="cluster-column supply" style={{height:`${Math.max(6,(node.supply??0)/max*100)}%`}}><b>{num(node.supply)}</b><small>عرضه</small></div>{node.demand!=null&&<div className="cluster-column demand" style={{height:`${Math.max(6,node.demand/max*100)}%`}}><b>{num(node.demand)}</b><small>تقاضا</small></div>}</div><div className={`cluster-balance ${(node.balance??0)>=0?"positive":"negative"}`}><small>{balanceText(node.balance)}</small><b>{node.balance==null?"—":`${node.balance>0?"+":""}${num(node.balance)}`}</b></div><h4>{node.product}</h4>{node.utilization!=null&&<div className="utilization-pill"><i style={{width:`${node.utilization}%`}}/><span>بهره‌وری {num(node.utilization,0)}٪</span></div>}</article>)}</div><footer>واحد تمام ارقام: میلیون تن</footer></section>
}

function CapacityColumns({group}:{group:"upstream"|"downstream"}){const rows=STEEL_CHAIN_DATA.groupCapacity[group],max=Math.max(...rows.flatMap(row=>[row.current,row.future]));return <article className="capacity-column-card"><header><div><small>{group==="upstream"?"زنجیره بالادست":"زنجیره پایین‌دست"}</small><h3>{group==="upstream"?"ظرفیت مواد و فولاد میانی":"ظرفیت محصولات تخت"}</h3></div><span>میلیون تن</span></header><div className="capacity-column-chart">{rows.map((row,index)=><div className="capacity-cluster" key={row.product} style={{"--delay":`${index*65}ms`} as React.CSSProperties}><div className="capacity-column-bars"><span className="capacity-column current" style={{height:`${row.current/max*100}%`}}><b>{num(row.current)}</b></span><span className="capacity-column future" style={{height:`${row.future/max*100}%`}}><b>{num(row.future)}</b></span></div><strong>{row.product}</strong></div>)}</div></article>}
function CapacityComparison({ filter }: { filter: string }) {const groups=filter==="all"?["upstream","downstream"] as const:[filter] as ("upstream"|"downstream")[];return <><div className="capacity-head"><div><small>ظرفیت گروه فولاد مبارکه</small><h3>ظرفیت فعلی گروه در برابر افق ۱۴۱۰</h3></div><div><span><i className="now"/>وضعیت فعلی</span><span><i className="future"/>افق ۱۴۱۰</span></div></div><section className={`capacity-columns-layout ${groups.length===1?"single":""}`}>{groups.map(group=><CapacityColumns group={group} key={group}/>)}</section></>}

function CompanyVerticalChart({rows,title,unit,multiplier=1}:{rows:readonly (typeof STEEL_CHAIN_DATA.mainCompany[number])[];title:string;unit:string;multiplier?:number}){const max=Math.max(...rows.flatMap(row=>[row.production1404,row.production1405,row.consumption1404,row.consumption1405,Math.abs(row.balance1404),Math.abs(row.balance1405)].map(value=>value*multiplier)),1);const digits=unit==="هزار تن"?0:2;return <section className="company-vertical-panel"><header><div><small>مقایسه عملکرد ۱۴۰۴ با پیش‌بینی ۱۴۰۵</small><h3>{title}</h3></div><span>{unit}</span></header><ChartLegend/><div className="company-vertical-scroll"><div className="company-vertical-chart">{rows.map((row,index)=><article key={row.product} style={{"--delay":`${index*70}ms`} as React.CSSProperties}><div className="company-product-clusters">{([1404,1405] as const).map(year=>{const production=row[`production${year}`]*multiplier,consumption=row[`consumption${year}`]*multiplier,balance=row[`balance${year}`]*multiplier;return <div className="company-year-cluster" key={year}><div className="company-positive-zone"><i className="production" style={{height:`${production/max*100}%`}}><b>{num(production,digits)}</b></i><i className="consumption" style={{height:`${consumption/max*100}%`}}><b>{consumption?num(consumption,digits):"—"}</b></i><i className={balance>=0?"balance positive":"balance ghost"} style={{height:`${Math.abs(balance)/max*100}%`}}>{balance>=0&&<b>+{num(balance,digits)}</b>}</i></div><div className="company-zero-line"/><div className="company-negative-zone">{balance<0&&<i style={{height:`${Math.abs(balance)/max*100}%`}}><b>{num(balance,digits)}</b></i>}</div><strong>{year.toLocaleString("fa-IR",{useGrouping:false})}</strong></div>})}</div><h4>{row.product}</h4><small>{relatedCompanies("شرکت فولاد مبارکه",row.product).join("، ")}</small></article>)}</div></div></section>}
function CompanyView() { const rows = STEEL_CHAIN_DATA.mainCompany; return <><div className="company-panels"><CompanyVerticalChart rows={rows.slice(0,4)} title="محصولات اصلی زنجیره" unit="میلیون تن"/><CompanyVerticalChart rows={rows.slice(4)} title="محصولات پایین‌دستی" unit="هزار تن" multiplier={1000}/></div><Message companies={relatedCompanies("شرکت فولاد مبارکه")}>مازاد گندله یک فرصت تجارت و صادرات ایجاد می‌کند. کسری اسلب در ۱۴۰۵ و کاهش عرضه ورق گرم، نیاز تأمین فولاد مبارکه و شرکت‌های پایین‌دستی گروه را افزایش می‌دهد.</Message></>}

function FutureView({ scenario }: { scenario: "18" | "utilization" | "downstream" }) { const data = STEEL_CHAIN_DATA.futureGroup[scenario]; return <><section className="steel-view-title"><div><small>سناریوی منتخب گروه</small><h2>{scenario === "downstream" ? "بازار اسلب و ورق گرم" : data.title}</h2></div><span>عرضه <i /> تقاضا <i /> موازنه</span></section><SupplyDemand nodes={data.nodes} /><Message companies={relatedCompanies("گروه فولاد مبارکه")}>{scenario === "18" ? "هدف ۱۸ میلیون تن فولاد میانی، در تمام حلقه‌های بالادست فشار تأمین ایجاد می‌کند و نقطه شروع آن معدن و سنگ‌آهن است." : scenario === "utilization" ? "با نرخ بهره‌وری فعلی نیز کسری در حلقه‌های میانی باقی می‌ماند؛ اولویت، سرمایه‌گذاری معدنی و توسعه تجارت داخلی کنسانتره، گندله و آهن اسفنجی است." : "در افق عرضه به بازار، اسلب و کلاف گرم مازاد دارند؛ این مازاد ظرفیت تجارت خارجی را ایجاد می‌کند."}</Message></>; }

function SteelMix(){const total=STEEL_CHAIN_DATA.national.nominalSteelCapacity.reduce((sum,item)=>sum+item.value,0);return <aside className="steel-mix"><header><small>جزئیات ظرفیت فولاد میانی</small><b>۶۴٫۷۸ میلیون تن ظرفیت اسمی</b></header><section className="steel-route-mix"><div><span>ترکیب ظرفیت بر مبنای مسیر تولید</span><b>{num(total)} میلیون تن</b></div><div className="steel-route-stack">{STEEL_CHAIN_DATA.national.nominalSteelCapacity.map((item,index)=><i key={item.label} className={`route-${index+1}`} style={{width:`${item.value/total*100}%`}}><strong>{num(item.value)}</strong></i>)}</div>{STEEL_CHAIN_DATA.national.nominalSteelCapacity.map((item,index)=><p key={item.label}><i className={`route-${index+1}`}/><span>{item.label}</span><b>{num(item.value)}</b></p>)}</section><section className="steel-product-mix"><div className="steel-mix-ring" style={{background:`conic-gradient(#1b82b7 0 71%,#e88d38 71% 100%)`}}><span>شکل محصول</span></div><div>{STEEL_CHAIN_DATA.national.nominalSteelMix.map(item=><p key={item.label}><i className={item.share>50?"billet":"slab"}/><span>{item.label}</span><b>{num(item.value)}<small>{num(item.share,0)}٪</small></b></p>)}</div></section></aside>}

function UtilizationComparison(){const current=STEEL_CHAIN_DATA.national.energy.nodes;return <section className="utilization-comparison"><header><div><small>بهره‌وری زنجیره بالادست</small><h3>افت نرخ بهره‌وری تحت محدودیت انرژی</h3></div><span>درصد بهره‌برداری از ظرفیت اسمی</span></header><div>{current.map((node)=>{const past=STEEL_CHAIN_DATA.national.historicalUtilization.find(item=>item.product===node.product)?.value??0;const constrained=node.utilization??0;return <article key={node.product}><h4>{node.product}</h4><div className="utilization-track"><i className="historical" style={{width:`${past}%`}}/><b>{num(past,0)}٪</b><span>روند گذشته</span></div><div className="utilization-track"><i className="constrained" style={{width:`${constrained}%`}}/><b>{num(constrained,0)}٪</b><span>با محدودیت انرژی</span></div><strong className={constrained<past?"down":"stable"}>{constrained===past?"بدون تغییر":`${num(past-constrained,0)} واحد درصد افت`}</strong></article>})}</div></section>}
function OreFlow(){
  const data: readonly SteelNode[]=STEEL_CHAIN_DATA.national.ore.nodes;
  return <section className="ore-flow-board"><header><div><small>سناریوی محدودیت عرضه سنگ‌آهن</small><h3>اثر محدودیت خوراک بر کل زنجیره</h3></div><span>عرضه بر مبنای ۱۲۵ میلیون تن استخراج داخلی</span></header><div className="ore-flow-track">{data.map((node,index)=>{
    const past=STEEL_CHAIN_DATA.national.historicalUtilization.find(item=>item.product===node.product)?.value;
    return <article key={node.product}><div className="ore-node"><small>{node.product}</small><b>{num(node.supply)}</b><em>میلیون تن</em></div>{node.utilization!=null&&<div className="ore-utilization"><div><span>سناریوی محدودیت</span><b>{num(node.utilization,0)}٪</b></div>{past!=null&&<div><span>بهره‌وری گذشته</span><b>{num(past,0)}٪</b></div>}</div>}{index<data.length-1&&<ArrowLeft/>}</article>
  })}</div></section>
}
function ScenarioMatrix(){const products=["کنسانتره","گندله","آهن اسفنجی","فولاد میانی"];return <section className="scenario-matrix"><header><div><small>ترکیب سناریوهای بهره‌وری</small><h3>میانگین وزنی نرخ بهره‌وری</h3></div><div>{STEEL_CHAIN_DATA.national.weights.map(item=><span key={item.label}>{item.label}<b>{num(item.value,0)}٪</b></span>)}</div></header><div className="scenario-table"><div className="scenario-table-head"><b>سناریو</b>{products.map(product=><b key={product}>{product}</b>)}</div>{STEEL_CHAIN_DATA.national.scenarioUtilization.map((row,index)=><div className={index===3?"likely-row":""} key={row.label}><span>{row.label}{index<3&&<small>وزن {num(row.weight,0)}٪</small>}</span>{row.values.map((value,valueIndex)=><b key={`${row.label}-${valueIndex}`}><i style={{"--value":`${value}%`} as React.CSSProperties}/>{num(value,0)}٪</b>)}</div>)}</div></section>}
function NationalView({ scenario }: { scenario: "nominal" | "energy" | "ore" | "likely" }) { const data = STEEL_CHAIN_DATA.national[scenario]; return <><div className="steel-scenario-strip">{topics.find((x) => x.id === "national")!.options.map((option) => <span className={option.id === scenario ? "active" : ""} key={option.id}>{option.label}</span>)}</div>{scenario==="ore"?<OreFlow/>:scenario==="likely"?<><ScenarioMatrix/><SupplyDemand nodes={data.nodes}/></>:scenario==="nominal"?<div className="national-nominal-layout"><SupplyDemand nodes={data.nodes}/><SteelMix/></div>:<><UtilizationComparison/><SupplyDemand nodes={data.nodes}/></>}<Message>{scenario === "nominal" ? "در فرض تحقق ظرفیت اسمی، سنگ‌آهن حدود ۳۰٫۷ میلیون تن کسری دارد؛ حلقه‌های کنسانتره، گندله و آهن اسفنجی مازاد خواهند داشت." : scenario === "energy" ? "محدودیت انرژی بیشترین افت بهره‌وری را در آهن اسفنجی و فولاد میانی ایجاد می‌کند؛ با این حال عرضه محاسبه‌شده در چهار حلقه از تقاضای درون‌زنجیره‌ای بیشتر می‌ماند." : scenario === "ore" ? "محدودشدن استخراج داخلی به ۱۲۵ میلیون تن، تولید حلقه‌های بعدی را کاهش می‌دهد و بهره‌وری آنها را پایین‌تر از روند گذشته قرار می‌دهد." : "سناریوی محتمل از وزن ۳۰ درصدی روند گذشته، ۵۰ درصدی محدودیت انرژی و ۲۰ درصدی محدودیت سنگ‌آهن ساخته شده است. نتیجه، فرصت سرمایه‌گذاری در معدن و تجارت خارجی فولاد میانی و آهن اسفنجی است."}</Message></>; }

function ProductView({ kind, scenario }: { kind: "slab" | "hot"; scenario: string }) { const product = STEEL_CHAIN_DATA.products[kind]; const data = kind === "hot" ? STEEL_CHAIN_DATA.products.hot.scenarios.market : STEEL_CHAIN_DATA.products.slab.scenarios[scenario === "nominal" ? "nominal" : "demand"];const max=Math.max(data.supply,data.demand);const colors=["#7041a5","#ed7d31","#2e884f"];return <><section className="product-hero"><div><small>{product.title}</small><h2>{data.label}</h2><p>عرضه، ترکیب تقاضا و موازنه · میلیون تن</p></div><BalanceBadge value={data.balance} /></section><section className="market-waterfall"><div className="market-columns"><article><b>{num(data.supply)}</b><div className="market-column supply" style={{height:`${data.supply/max*260}px`,flexShrink:0}}/><span>عرضه</span><small>{scenario==="nominal"?"ظرفیت اسمی":"پیش‌بینی تولید"}</small></article><article><b>{num(data.demand)}</b><div className="market-column demand-stack" style={{height:`${data.demand/max*260}px`,flexShrink:0}}>{data.breakdown.map((item,index)=><i key={item.label} style={{height:`${item.value/data.demand*100}%`,background:colors[index]}}><em>{num(item.value)}</em></i>)}</div><span>تقاضا</span><small>مجموع اجزای مصرف</small></article><article className="balance-column"><b className={data.balance>=0?"positive":"negative"}>{data.balance>0?"+":""}{num(data.balance)}</b><div className={data.balance>=0?"market-column balance-positive":"market-column balance-negative"} style={{height:`${Math.abs(data.balance)/max*260}px`,flexShrink:0}}/><span>{balanceText(data.balance)}</span><small>موازنه بازار</small></article></div><aside className="market-breakdown"><header><small>ترکیب تقاضا</small><b>{num(data.demand)} میلیون تن</b></header>{data.breakdown.map((item,index)=><div key={item.label}><i style={{background:colors[index]}}/><span>{item.label}</span><b>{num(item.value)}</b><small>{num(item.value/data.demand*100,0)}٪</small></div>)}</aside></section><Message companies={relatedCompanies("کشور",kind === "hot" ? "کلاف گرم" : "اسلب")}>{kind === "slab" ? scenario==="nominal"?"ظرفیت اسمی اسلب اندکی کمتر از تقاضای متناظر است؛ در این حالت فرصت سرمایه‌گذاری جدید دیده نمی‌شود.":"در سناریوی محتمل، عرضه اسلب ۲٫۶۳ میلیون تن بیش از تقاضاست؛ مسیر تصمیم، توسعه سرمایه‌گذاری جدید نیست و استفاده از فرصت تجارت خارجی است." : "بازار کلاف گرم در افق ۱۴۱۰ حدود ۶٫۸۸ میلیون تن مازاد دارد. این وضعیت فرصت محدود تجارت خارجی ایجاد می‌کند و هم‌زمان تهدید تأمین برای فولاد متیل را باید پایش کرد."}</Message></>; }

function TradeView({ product }: { product: string }) { const item = STEEL_CHAIN_DATA.trade.series.find((x) => x.product === product) ?? STEEL_CHAIN_DATA.trade.series[0]; const max = Math.max(...item.values); return <><section className="trade-card"><header><div><small>شواهد تجارت و صادرات</small><h2>{item.product}</h2><p>روند تاریخی صادرات · واحد: هزار تن</p></div><span>{num(item.values.at(-1), 2)}<small>آخرین دوره</small></span></header><div className="trade-chart">{item.values.map((value, index) => <div key={STEEL_CHAIN_DATA.trade.years[index]}><b>{num(value, 0)}</b><i style={{ height: `${value / max * 100}%` }} /><small>{STEEL_CHAIN_DATA.trade.years[index].replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[Number(d)])}</small></div>)}</div></section><p className="trade-period-note">دوره ۱۴۰۴ ده‌ماهه است؛ با سال کامل مقایسه مستقیم نشود.</p><div className="steel-companies"><Building2/>{item.companies.map(name=><b key={name}>{name}</b>)}</div><Message>شواهد تجارت تاریخی باید کنار موازنه آتی خوانده شود: مازاد عرضه تنها زمانی به فرصت تبدیل می‌شود که مسیر بازاررسانی و صادرات محصول فعال باشد.</Message></>; }

export default function SteelChainAnalysis({ onBack }: { onBack: () => void }) {
  const [topic, setTopic] = useState<Topic>("group"); const [sub, setSub] = useState("all");
  const selected = useMemo(() => topics.find((item) => item.id === topic)!, [topic]);
  const chooseTopic = (next: Topic) => { const item = topics.find((x) => x.id === next)!; setTopic(next); setSub(item.options[0].id); };
  const content = topic === "group" ? <CapacityComparison filter={sub} /> : topic === "company" ? <CompanyView /> : topic === "future" ? <FutureView scenario={sub as "18" | "utilization" | "downstream"} /> : topic === "national" ? <NationalView scenario={sub as "nominal" | "energy" | "ore" | "likely"} /> : topic === "slab" ? <ProductView kind="slab" scenario={sub} /> : topic === "hot" ? <ProductView kind="hot" scenario={sub} /> : <TradeView product={sub} />;
  return <section className="steel-analysis" aria-label="تحلیل زنجیره فولاد"><header className="steel-header"><button onClick={onBack} className="steel-back"><ChevronLeft /> بازگشت به جایگاه بازار</button><div><span className="overline">بازار و تجارت · ۱۴۰۵</span><h2>تحلیل زنجیره فولاد</h2><p>تصویر یکپارچه ظرفیت، موازنه و شواهد تجارت؛ از زنجیره گروه تا بازار کشور</p></div><div className="steel-header-mark"><Factory /><span>داشبورد<br />مدیریتی</span></div></header><section className="steel-controls"><label><small>موضوع تحلیل</small><select value={topic} onChange={(e) => chooseTopic(e.target.value as Topic)}>{topics.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label><small>نمای مرتبط</small><select value={sub} onChange={(e) => setSub(e.target.value)}>{selected.options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div className="steel-source"><Layers3 /><span>واحد بازار: میلیون تن<br />تجارت: هزار تن</span></div></section><div className="steel-stage" key={`${topic}-${sub}`}>{content}</div></section>;
}
