"use client";
import {useState} from 'react';
import {coreConnection,type CoreRow} from '@/lib/core-connection.mjs';
import {TRADE_CRITERIA,STEEL_CRITERIA,LEVELS,newTradeRoute,routeAssessment,type TradeRoute} from '@/lib/trade-development.mjs';
import {workspaceId} from '@/lib/scenario-workspace.mjs';
const fa=(n:number|null)=>n==null?'ارزیابی نشده':n.toLocaleString('fa-IR');
export default function TradeDevelopmentLens({rows,selected,routes,onChange}:{rows:CoreRow[];selected:{parentId:number}[];routes:TradeRoute[];onChange:(routes:TradeRoute[])=>void}){
 const [all,setAll]=useState(false),[edit,setEdit]=useState<string|null>(null),[parent,setParent]=useState(rows[0]?.id??1);
 const [search,setSearch]=useState(''),[page,setPage]=useState(0);
 const selectedIds=new Set(selected.map(r=>r.parentId));const shown=all?rows:rows.filter(r=>selectedIds.has(r.id));
 const filtered=shown.filter(r=>r.name.includes(search)||routes.some(t=>t.parentId===r.id&&t.title.includes(search)));const pages=Math.max(1,Math.ceil(filtered.length/10));const activePage=Math.min(page,pages-1);const pageRows=filtered.slice(activePage*10,(activePage+1)*10);
 const visible=routes.filter(r=>shown.some(x=>x.id===r.parentId));const current=routes.find(r=>r.id===edit);
 const patch=(p:Partial<TradeRoute>)=>current&&onChange(routes.map(r=>r.id===current.id?{...r,...p}:r));
 const points=visible.map(r=>({r,a:routeAssessment(r)})).filter(p=>p.a.complete);
 return <section className="trade-development" aria-label="فرصت‌های توسعه بازرگانی">
 <header><div><span>جمع‌بندی مسیر حرکت</span><h3>فرصت‌های توسعه بازرگانی</h3><p>کدام مسیر ورود، از توان بازرگانی موجود ما استفاده می‌کند؟</p></div><b>{fa(visible.filter(r=>routeAssessment(r).complete).length)} مسیر مستند / {fa(visible.length)} مسیر</b></header>
 <p className="trade-note">دو بعد مستقل‌اند: نزدیکی به فولاد و قابلیت توسعه بازرگانی. این ارزیابی در امتیاز انتخاب و تخصیص مالی وارد نمی‌شود. برای یک حوزه می‌توان چند مسیر ورود تعریف کرد.</p>
 <nav aria-label="دامنه توسعه بازرگانی"><button aria-pressed={!all} onClick={()=>{setAll(false);setPage(0);setEdit(null);}}>حوزه‌های منتخب</button><button aria-pressed={all} onClick={()=>{setAll(true);setPage(0);setEdit(null);}}>همه حوزه‌ها</button></nav>
 <div className="trade-add"><label>حوزه مسیر جدید<select value={parent} onChange={e=>setParent(Number(e.target.value))}>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button onClick={()=>{const r=newTradeRoute(workspaceId(),parent);onChange([...routes,r]);setEdit(r.id);setSearch('');setPage(0);if(!selectedIds.has(parent))setAll(true);}}>تعریف مسیر توسعه</button></div>
 <label className="trade-search">جستجوی حوزه یا مسیر<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="نام حوزه یا مسیر توسعه"/></label>
 <div className="table-scroll"><table className="trade-table"><thead><tr><th>حوزه / مسیر توسعه</th><th>نزدیکی به فولاد</th><th>قابلیت بازرگانی</th><th>محصول، مشتری و کانال</th><th>شکاف ورود / مبنا</th><th>ارزیابی</th></tr></thead><tbody>{pageRows.flatMap(row=>{const rr=visible.filter(r=>r.parentId===row.id);return rr.length?rr.map(r=>{const a=routeAssessment(r);return <tr key={r.id}><td><b>{row.name}</b><small>{r.title||'مسیر بدون عنوان'}</small></td><td>{fa(a.steel.score)}<small>{fa(a.steel.covered)} از {fa(a.steel.total)} معیار مستند</small></td><td>{fa(a.trade.score)}<small>{fa(a.trade.covered)} از {fa(a.trade.total)} معیار مستند</small></td><td>{r.product||'محصول نامشخص'}<small>{r.customer||'مشتری نامشخص'} · {r.channel||'کانال نامشخص'}</small></td><td>{r.gap||'تکمیل نشده'}<small>{r.reviewer||'ارزیاب ثبت نشده'} · {r.reviewedAt||'تاریخ ثبت نشده'}</small></td><td><button onClick={()=>setEdit(r.id)}>{a.label} · ویرایش</button></td></tr>;}):[<tr key={row.id}><td><b>{row.name}</b></td><td>ارزیابی نشده</td><td>ارزیابی نشده</td><td colSpan={2}>{coreConnection(row).capability}<small>سرنخ پیشنهادی مدل؛ امتیاز قابلیت واقعی نیست</small></td><td><button onClick={()=>{const r=newTradeRoute(workspaceId(),row.id);onChange([...routes,r]);setEdit(r.id);}}>تعریف مسیر</button></td></tr>];})}</tbody></table>{!shown.length&&<p>هنوز حوزه‌ای در سبد منتخب نیست؛ برای کشف مسیرها، «همه حوزه‌ها» را باز کنید.</p>}</div>
 <div className="trade-pagination"><button disabled={activePage===0} onClick={()=>setPage(activePage-1)}>صفحه قبل</button><span>صفحه {fa(activePage+1)} از {fa(pages)} · {fa(filtered.length)} حوزه</span><button disabled={activePage>=pages-1} onClick={()=>setPage(activePage+1)}>صفحه بعد</button></div>
 {current&&<section className="trade-editor" aria-label="ارزیابی مسیر توسعه"><header><h4>ارزیابی مسیر · {rows.find(r=>r.id===current.parentId)?.name}</h4><button onClick={()=>setEdit(null)}>بستن ارزیابی</button><button onClick={()=>{onChange(routes.filter(r=>r.id!==current.id));setEdit(null);}}>حذف مسیر جاری</button></header><p>هر معیار از صفر تا چهار، همراه با شاهد یا دلیل ثبت می‌شود. نبود پیوند را با صفر و دلیل ثبت کنید؛ داده ناموجود را خالی بگذارید.</p><div className="trade-fields">{([['title','عنوان مسیر ورود'],['product','چه محصول یا خدمتی؟'],['customer','برای کدام مشتری؟'],['channel','از کدام کانال؟'],['gap','قابلیت جدید موردنیاز / شکاف ورود'],['reviewer','نام ارزیاب'],['reviewedAt','تاریخ ارزیابی']] as const).map(([k,label])=><label key={k}>{label}<input maxLength={2000} value={current[k]} onChange={e=>patch({[k]:e.target.value})}/></label>)}</div>{([['steel','نزدیکی به زنجیره فولاد',STEEL_CRITERIA],['trade','قابلیت توسعه بازرگانی',TRADE_CRITERIA]] as const).map(([d,title,criteria])=><fieldset key={d}><legend>{title}</legend>{criteria.map(([k,label])=><div className="trade-criterion" key={k}><label>{label}<select value={current[d][k].level??''} onChange={e=>patch({[d]:{...current[d],[k]:{...current[d][k],level:e.target.value===''?null:Number(e.target.value)}}})}><option value="">ارزیابی نشده</option>{LEVELS.map((l,i)=><option key={i} value={i}>{fa(i)} · {l}</option>)}</select></label><label>شاهد، منبع یا دلیل<input maxLength={2000} value={current[d][k].evidence} onChange={e=>patch({[d]:{...current[d],[k]:{...current[d][k],evidence:e.target.value}}})}/></label></div>)}</fieldset>)}<p className="trade-note">{routeAssessment(current).label} · فولاد: {fa(routeAssessment(current).steel.score)} · بازرگانی: {fa(routeAssessment(current).trade.score)}. تغییرات در سناریوی جاری ذخیره می‌شوند و در پشتیبان آن قرار می‌گیرند.</p></section>}
 <details className="trade-map"><summary>نقشه مقایسه مسیرهای مستند ({fa(points.length)})</summary>{points.length?<><svg viewBox="0 0 620 390" role="img" aria-label="افقی: نزدیکی به فولاد؛ عمودی: قابلیت توسعه بازرگانی"><rect x="60" y="20" width="520" height="300" fill="#f3f8fb"/>{[0,25,50,75,100].map(n=><g key={n}><line x1={60+n*5.2} x2={60+n*5.2} y1="20" y2="320" stroke="#d8e5ed"/><line x1="60" x2="580" y1={320-n*3} y2={320-n*3} stroke="#d8e5ed"/><text x={60+n*5.2} y="340" textAnchor="middle">{fa(n)}</text><text x="40" y={324-n*3} textAnchor="middle">{fa(n)}</text></g>)}{points.map(({r,a},i)=><g key={r.id}><circle cx={60+a.steel.score!*5.2} cy={320-a.trade.score!*3} r="9" fill="#187a68"/><text x={60+a.steel.score!*5.2} y={324-a.trade.score!*3} textAnchor="middle" fill="#fff" fontSize="10">{fa(i+1)}</text></g>)}<text x="320" y="375" textAnchor="middle">نزدیکی به زنجیره فولاد</text><text x="18" y="170" transform="rotate(-90 18 170)" textAnchor="middle">قابلیت توسعه بازرگانی</text></svg><div className="trade-point-list">{points.map(({r,a},i)=><button key={r.id} onClick={()=>setEdit(r.id)}>{fa(i+1)} · {r.title} — فولاد {fa(a.steel.score)} / بازرگانی {fa(a.trade.score)}</button>)}</div></>:<p>نقشه پس از تکمیل معیارها، شواهد و مشخصات مسیر نمایش داده می‌شود.</p>}</details>
 <details><summary>روش ارزیابی و اعتبار امتیاز</summary><p>نسخه روش: ۱. در هر بعد، میانگین معیارهای صفر تا چهار × ۲۵ است. وزن‌ها در این نسخه برابر و موقت‌اند؛ پس از کالیبراسیون با نمونه‌های واقعی قابل بازنگری‌اند. امتیاز، قضاوت مستند مدیریتی است و درصد احتمال موفقیت یا جذابیت اقتصادی نیست. هر بعد فقط پس از تکمیل همه معیارها و شواهد عدد می‌گیرد. داده حوزه مادر به زیرحوزه ارث داده نمی‌شود؛ مسیر باید محصول و مشتری مشخص داشته باشد. امتیاز ترکیبی ساخته نمی‌شود.</p></details>
 </section>;
}
