"use client";
import {useMemo,useState} from 'react';
import {sortProximity,type ProximityMetric} from '@/lib/proximity-sort.mjs';
import type {CoreRow} from '@/lib/core-connection.mjs';
import {tradeExpansion as tradingProximity,tradeExpansionCsv as proximityCsv} from '@/lib/trade-expansion.mjs';
const fa=(n:number|null,d=1)=>n==null?'داده موجود نیست':n.toLocaleString('fa-IR',{maximumFractionDigits:d});
export default function TradingProximityRanking({rows,selected,year,mission}:{rows:CoreRow[];selected:{parentId:number}[];year:number;mission?:Record<number,string>}){
 const [metric,setMetric]=useState<ProximityMetric>('score');
 const [sort,setSort]=useState<'desc'|'asc'>('desc'),[group,setGroup]=useState('همه مسیرها'),[search,setSearch]=useState(''),[onlySelected,setOnlySelected]=useState(false),[page,setPage]=useState(0),[open,setOpen]=useState<number|null>(null);
 const ranked=useMemo(()=>tradingProximity(rows),[rows]),selectedIds=new Set(selected.map(r=>r.parentId));
 const filtered=sortProximity(ranked.filter(r=>(group==='همه مسیرها'||r.group===group)&&(!onlySelected||selectedIds.has(r.id))&&[r.name,r.expansion,r.connection].some(x=>x.includes(search.trim()))),metric,sort);
 const sortBy=(key:ProximityMetric)=>{setMetric(key);setSort(metric===key&&sort==='desc'?'asc':'desc');setPage(0);};
 const metricLabel={score:'امتیاز کل',service:'بازرگانی',steel:'پیوند فولاد'};
 const pages=Math.max(1,Math.ceil(filtered.length/12)),activePage=Math.min(page,pages-1),visible=filtered.slice(activePage*12,(activePage+1)*12);
 const leading=filtered.filter(r=>r.id!==41&&r[metric]!=null);
 const known=ranked.filter(r=>r.score!=null).length;
 const exportCsv=()=>{const url=URL.createObjectURL(new Blob([proximityCsv(ranked,[...selectedIds])],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`IPS-77-Trading-Proximity-${year}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="trading-ranking" aria-label="رتبه‌بندی ۷۷ حوزه برای توسعه بازرگانی فولاد">
 <header><div><span>انتهای مسیر حرکت · لنز توسعه بازرگانی</span><h3>کدام حوزه‌ها به بازرگانی فولاد ما نزدیک‌ترند؟</h3><p>رتبه‌بندی آماده برای مقایسه حوزه‌ها و تشخیص مسیر توسعه تجارت</p></div><div className="trading-coverage"><b>{fa(known,0)} / {fa(ranked.length,0)}</b><span>حوزه دارای امتیاز آماده</span></div></header>
 <div className="trading-purpose"><b>این جدول برای انتخاب چه می‌دهد؟</b><p>کنار جذابیت اقتصادی، ببینید کدام حوزه می‌تواند ادامه کسب‌وکار تجاری ما باشد و چه محصول یا خدمتی به شبکه فعلی اضافه کند. امتیاز بالاتر یعنی نزدیکی نسبی بیشتر در مدل؛ مجوز ورود یا تضمین سودآوری نیست.</p></div>
 <h4 className="proximity-leading-title">حوزه‌های نخست در نمایش جاری · {metricLabel[metric]}</h4><div className="trading-leading" aria-label="حوزه‌های نخست با معیار و فیلتر جاری">{leading.slice(0,4).map(r=><article key={r.id}><span>{r.name}</span><b>{fa(r[metric])} <small>از ۱۰۰</small></b><div className="trading-meter"><i style={{width:`${r[metric]}%`}}/></div><small>{r.connection}</small></article>)}</div>
 <div className="trading-toolbar"><label>مرتب‌سازی بر اساس<select value={metric} onChange={e=>{setMetric(e.target.value as ProximityMetric);setPage(0);}}><option value="score">امتیاز کل</option><option value="service">امتیاز بازرگانی</option><option value="steel">امتیاز پیوند فولاد</option></select></label><label>ترتیب نمایش<select value={sort} onChange={e=>{setSort(e.target.value as 'asc'|'desc');setPage(0);}}><option value="desc">بیشترین امتیاز اول</option><option value="asc">کمترین امتیاز اول</option></select></label><nav aria-label="دامنه رتبه‌بندی"><button aria-pressed={!onlySelected} onClick={()=>{setOnlySelected(false);setPage(0);}}>همه {fa(ranked.length,0)} حوزه</button><button aria-pressed={onlySelected} onClick={()=>{setOnlySelected(true);setPage(0);}}>منتخب‌های سال {year.toLocaleString('fa-IR',{useGrouping:false})}</button></nav><label>نوع توسعه<select value={group} onChange={e=>{setGroup(e.target.value);setPage(0);}}>{["همه مسیرها","توسعه محصول و مشتری","پشتیبان اجرای تجارت","بازار جدید / ارتباط غیرمستقیم"].map(g=><option key={g}>{g}</option>)}</select></label><label>جستجوی حوزه یا مسیر<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="مثلاً مواد شیمیایی، حمل یا تجهیزات"/></label><button onClick={exportCsv}>دریافت جدول کامل CSV</button></div>
 <div className="table-scroll"><table className="trading-table"><thead><tr><th>رتبه کل</th><th>حوزه</th>{(['service','steel','score'] as const).map(key=><th key={key} aria-sort={metric===key?(sort==='desc'?'descending':'ascending'):'none'}><button className={metric===key?'active':''} onClick={()=>sortBy(key)}>{metricLabel[key]} <span aria-hidden="true">{metric===key?(sort==='desc'?'↓':'↑'):'↕'}</span></button></th>)}<th>چرا / از چه مسیری؟</th><th>چه چیزی به بازرگانی اضافه کنیم؟</th><th>وضعیت در سناریو</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} data-proximity-id={r.id} className={selectedIds.has(r.id)?'trading-selected':''}><td>{fa(r.rank,0)}</td><td><b>{r.name}</b><small>کد حوزه {fa(r.id,0)} · {r.group}</small></td>{(['service','steel','score'] as const).map(key=><td key={key} className={`proximity-cell ${key} ${metric===key?'sorted':''}`}><div className="trading-score"><strong>{fa(r[key])}</strong>{r[key]!=null&&<small>از ۱۰۰</small>}</div><div className="trading-meter"><i style={{width:`${r[key]??0}%`}}/></div>{key==='score'&&<><button className="trading-basis" aria-expanded={open===r.id} onClick={()=>setOpen(open===r.id?null:r.id)}>مبنای عدد</button>{open===r.id&&<div className="trading-evidence"><p>شباهت خدمات بازرگانی: {fa(r.service)} از ۱۰۰</p><p>پیوند معاملاتی فولاد: {fa(r.steel)} از ۱۰۰</p><p>امتیاز کل = جذر حاصل‌ضرب دو مؤلفه</p><p>مؤلفه محدودکننده: {r.limiter}</p><p>ضریب مستقیم فولاد: {fa(r.steelVertical,6)} · Fit قبلی: {fa(r.raw,6)}</p></div>}</>}</td>)}<td><b>{r.connection}</b><p>محدودکننده عدد: {r.limiter}</p><p>{r.reason}</p></td><td>{r.expansion}<small>پیشنهاد تحلیلی؛ نیازمند بررسی محصول و مشتری</small></td><td><span>{selectedIds.has(r.id)?'در سبد منتخب':'در سبد نیست'}</span><small>مأموریت: {mission?.[r.id]??'تعیین نشده'}</small></td></tr>)}</tbody></table>{!visible.length&&<p className="trading-empty">حوزه‌ای با این فیلتر یافت نشد؛ دامنه یا عبارت جستجو را تغییر دهید.</p>}</div>
 <div className="trading-pagination"><button disabled={activePage===0} onClick={()=>setPage(activePage-1)}>صفحه قبل</button><span>{fa(filtered.length,0)} حوزه · صفحه {fa(activePage+1,0)} از {fa(pages,0)} · مرتب‌سازی: {metricLabel[metric]} · رتبه‌ها مربوط به کل مدل‌اند</span><button disabled={activePage>=pages-1} onClick={()=>setPage(activePage+1)}>صفحه بعد</button></div>

 </section>;
}
