export const ENTRY_MODES={direct:{label:'سرمایه‌گذاری مستقیم',target:'توسعه ظرفیت و دارایی عملیاتی',description:'ورود از مسیر احداث، توسعه، تملک یا مشارکت در فعالیت حوزه'},trade:{label:'توسعه بازرگانی',target:'تقویت هسته بازرگانی فولاد',description:'ورود از مسیر تأمین، فروش، توزیع یا خدمات مکمل معامله'}};
export function validEntryMetadata(item){
 if(!item||typeof item!=='object'||(item.entryMode!=null&&!Object.hasOwn(ENTRY_MODES,item.entryMode)))return false;
 const t=item.selectionTrace;if(t==null)return true;
 const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
 return object(t)&&t.version===1&&typeof t.chosenAt==='string'&&Number.isFinite(Date.parse(t.chosenAt))&&typeof t.dataSnapshot==='string'&&Number.isInteger(t.year)&&t.year>=1406&&t.year<=1414&&Number.isInteger(t.parentId)&&t.parentId>=1&&t.parentId<=77&&typeof t.child==='boolean'&&object(t.gates)&&typeof t.gates.mission==='string'&&object(t.scores)&&['macro','detail','management','priority'].every(k=>Object.hasOwn(t.scores,k)&&(t.scores[k]==null||Number.isFinite(t.scores[k])))&&object(t.weights)&&['macro','detail','board'].every(k=>Number.isFinite(t.weights[k])&&t.weights[k]>=0)&&Math.abs(t.weights.macro+t.weights.detail+t.weights.board-100)<.01;
}
export function captureSelectionTrace(opportunity,base,parent,year,dataSnapshot){
 return structuredClone({version:1,chosenAt:new Date().toISOString(),year,dataSnapshot,parentId:opportunity.parentId,child:opportunity.child,gates:{mission:base.mission?.[opportunity.parentId]??'تعیین نشده',condition:base.conditions?.[opportunity.parentId]??null,focus:base.focus?.[opportunity.parentId]??parent?.focus??'تعیین نشده',focusOverride:base.focusOverride?.[opportunity.parentId]??null,thresholds:base.thresholds},scores:{market:parent?.x??null,strategic:parent?.dynamicY??null,macro:opportunity.macro,detail:opportunity.detail,management:opportunity.management,priority:opportunity.entryPriority},weights:base.selectionWeights,vision:base.vision,isicPreset:base.isicPreset,isicWeights:base.customWeights,managementReason:opportunity.child?base.activityBoard?.[opportunity.key.replace('activity:','')]?.reason??'':base.board?.[opportunity.parentId]?.reason??''});
}
