/* مدیریت چند طرح، مقایسه هفتگی و کنترل کیفیت فایل‌های ورودی */
const portfolio=new Map();let activeKey=null;
const baseInit=init,baseRender=render;
const keyOf=s=>String(s||'').replace(/[\s‌،()\u200c]/g,'').replace('زمینشهرکصنعتی','شهرکصنعتی');
function latestKey(name){let date=String(name).match(/14\d\d[-_/]\d\d[-_/]\d\d/);return date?date[0].replace(/\D/g,''):'00000000'}
function snapshot(){return {model,title:$('title').textContent,meta:$('meta').textContent,date:$('date').textContent,sourceName,selected,stamp:latestKey(sourceName)}}
function activate(key){let s=portfolio.get(key);if(!s)return;activeKey=key;model=s.model;sourceName=s.sourceName;selected=s.selected;$('title').textContent=s.title;$('meta').textContent=s.meta;$('date').textContent=s.date;$('week').innerHTML=model.weeks.map((w,i)=>`<option value="${i}">${escapeHtml(w.label)}</option>`).join('');$('week').value=selected;$('dashboard').style.display='';document.querySelector('.empty')?.remove();render();updatePortfolio()}
function updatePortfolio(){let entries=Array.from(portfolio.entries());$('portfolio').classList.toggle('show',entries.length>1);$('portfolioCount').textContent=fa(entries.length)+' طرح ثبت‌شده در این نشست';$('portfolioItems').innerHTML=entries.map(([key,s])=>{let i=s.selected,plan=s.model.physical.reduce((a,t)=>a+t.weight*t.plan[i],0),actual=s.model.physical.reduce((a,t)=>a+t.weight*(t.actual[i]??0),0);return `<button type="button" class="project-tab ${key===activeKey?'active':''}" data-key="${escapeHtml(key)}"><b>${escapeHtml(s.title)}</b><small>پیشرفت ${pct(actual)} · فاصله ${(actual-plan>0?'+':'')+pct(actual-plan)}</small></button>`}).join('');$('portfolioItems').querySelectorAll('button').forEach(el=>el.onclick=()=>activate(el.dataset.key))}
init=function(data,name){baseInit(data,name);const s=snapshot(),key=keyOf(s.title);let old=portfolio.get(key);if(!old||s.stamp>=old.stamp)portfolio.set(key,s);activate(key)};
render=function(){baseRender();if(!model)return;let v=values(),i=v.i,prev=i-1,physical=model.physical,financial=model.financial,weighted=j=>physical.reduce((a,t)=>a+t.weight*(t.actual[j]??0),0),planned=j=>physical.reduce((a,t)=>a+t.weight*t.plan[j],0),delta=prev>=0?weighted(i)-weighted(prev):null,gapChange=prev>=0?(v.actual-v.planned)-(weighted(prev)-planned(prev)):null,weekPaid=billion(financial.reduce((a,f)=>a+f.paid[i],0));$('weeklyGrowth').textContent=delta==null?'—':(delta>0?'+':'')+pct(delta);$('weeklyGap').textContent=gapChange==null?'—':(gapChange>0?'+':'')+pct(gapChange);$('weeklyPaid').textContent=fa(weekPaid)+' میلیارد تومان';$('weeklyGap').className=gapChange<-.0001?'red':gapChange>.0001?'green':'';
 let bottlenecks=physical.map(t=>({name:t.name,owner:t.owner,plan:t.plan[i],actual:t.actual[i],impact:t.weight*Math.max(0,t.plan[i]-(t.actual[i]??0))})).filter(t=>t.plan>0&&t.actual!=null&&t.impact>.00001).sort((a,b)=>b.impact-a.impact);$('blockers').innerHTML=bottlenecks.length?bottlenecks.slice(0,3).map((t,j)=>`<div class="blocker"><div class="eyebrow">اولویت ${fa(j+1)}</div><b>${escapeHtml(t.name)}</b><span>اثر بر کل طرح: ${pct(t.impact)} واحد درصد · ${escapeHtml(t.owner||'مجری ثبت نشده')}</span></div>`).join(''):'<div class="blocker" style="grid-column:1/-1"><b>گلوگاه دارای عقب‌ماندگی ثبت نشده است.</b><span>بر اساس داده‌های هفته انتخابی</span></div>';$('blockerNote').textContent='اثر بر کل طرح = وزن فعالیت × عقب‌ماندگی همان فعالیت. این رتبه‌بندی جایگزین بررسی مسیر بحرانی زمان‌بندی نیست.';
 let issues=[],weight=physical.reduce((a,t)=>a+t.weight,0);if(Math.abs(weight-1)>.0001)issues.push('جمع وزن‌ها '+pct(weight)+' است.');if(physical.some(t=>t.weight<0||t.weight>1||t.plan.some(n=>n<0||n>1)||t.actual.some(n=>n!=null&&(n<0||n>1))))issues.push('درصد یا وزن خارج از بازه صفر تا ۱۰۰٪ ثبت شده است.');if(physical.some(t=>t.actual.some((n,j)=>j>0&&n!=null&&t.actual[j-1]!=null&&n+1e-8<t.actual[j-1])))issues.push('عملکرد تجمیعی دست‌کم یک فعالیت نسبت به هفته قبل کاهش یافته است.');let missing=physical.filter(t=>t.plan[i]>0&&t.actual[i]==null);if(missing.length)issues.push('برای '+fa(missing.length)+' فعالیت برنامه‌دار، عملکرد هفته انتخابی خالی است؛ اختلاف آن‌ها قطعی تلقی نشود.');let cap=financial.reduce((a,t)=>a+t.cost,0);if(v.paid>cap+.001)issues.push('پرداخت ثبت‌شده از برآورد کل هزینه بیشتر است.');$('quality').innerHTML='<b>کنترل کیفیت گزارش:</b> '+(issues.length?issues.map(escapeHtml).join(' · '):'ایراد آشکار در دامنه اعداد و روند تجمیعی دیده نشد.')+'<br><span>پرداخت و بودجه از مقادیر هفتگی شیت مالی جمع می‌شوند. تعهدات، صورت‌وضعیت‌های پرداخت‌نشده و برآورد هزینه تکمیل در فایل ورودی وجود ندارند؛ بنابراین مانده برآورد پس از پرداخت معادل نیاز نقدی قطعی نیست.</span>';
 let warnings=issues.filter(x=>!x.startsWith('جمع وزن‌ها'));if(warnings.length){$('banner').textContent=[...issues].join(' ');$('banner').classList.add('show')}if(activeKey&&portfolio.has(activeKey))portfolio.get(activeKey).selected=selected;
};
$('file').addEventListener('change',async e=>{let files=Array.from(e.target.files||[]);if(!files.length)return;let failures=[];for(let file of files){try{let parsed=await parseXlsx(file);init(parsed,file.name)}catch(err){failures.push(file.name+': '+err.message)}}if(failures.length){$('banner').textContent=failures.join(' | ');$('banner').classList.add('show')}e.target.value=''});
fetch('./sample.json').then(r=>{if(!r.ok)throw Error('نمونه ندارد');return r.json()}).then(d=>init(d,'روند پیشرفت امور مربوط به زمین کوهپایه 1405-06-28.xlsx')).catch(()=>{if(model)return;$('dashboard').style.display='none';let box=document.createElement('section');box.className='empty';box.innerHTML='<h2>داشبورد برای دریافت گزارش آماده است</h2><p>فایل اکسل دوشیتی طرح را بارگذاری کنید. می‌توانید چند فایل از طرح‌های مختلف را هم‌زمان انتخاب کنید.</p><label class="upload" for="file">انتخاب فایل اکسل</label>';document.querySelector('main').append(box)});
